repos:
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: clippy
        name: cargo clippy
        entry: cargo clippy --workspace -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=3000']
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: end-of-file-fixer
        exclude: ^(docs/|book/)
      - id: trailing-whitespace
        exclude: ^(docs/|book/)
      - id: mixed-line-ending
        args: ['--fix=lf']
