// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/frankfurter.md
#![allow(unused)]

// line 14: compile-only (no_run)
#[cfg(feature = "frankfurter")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_14() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::FOREX, [Provider::Frankfurter])
            .build()
            .await?;

        let quote = providers.forex("USD", "EUR").quote().await?;
        println!("USD/EUR {:?} ({:+.2?}%)", quote.price, quote.change_percent);
        Ok(())
    }
}

// line 48: compile-only (no_run)
#[cfg(feature = "full")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_48() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::FOREX, [Provider::Polygon, Provider::Frankfurter])
            .build()
            .await?;
        Ok(())
    }
}
