// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/fmp.md
#![allow(unused)]

// line 25: compile-only (no_run)
#[cfg(feature = "fmp")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_25() {
    use finance_query::format::Raw;
    use finance_query::{Capability, Fetch, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::QUOTE, [Provider::Fmp, Provider::Yahoo])
            .fetch(Fetch::Sequential)
            .build()
            .await?;
        let ticker = providers.ticker("AAPL").build().await?;
        let quote = ticker.quote::<Raw>().await?;
        println!("{} quote received", quote.symbol);
        Ok(())
    }
}
