// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/finra.md
#![allow(unused)]

// line 17: compile-only (no_run)
#[cfg(feature = "finra")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_17() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::FUNDAMENTALS, [Provider::Finra, Provider::Yahoo])
            .build()
            .await?;

        let ticker = providers.ticker("AAPL").build().await?;
        for day in ticker.short_volume().await? {
            println!(
                "{} short {:?} of {:?}",
                day.date.unwrap_or_default(),
                day.short_volume,
                day.total_volume
            );
        }
        Ok(())
    }
}
