// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/feeds.md
#![allow(unused)]

// line 15: compile-only (no_run)
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_15() {
    use finance_query::feeds::{self, FeedSource};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        // Federal Reserve press releases and speeches
        let fed_news = feeds::fetch(FeedSource::FederalReserve).await?;

        for entry in fed_news.iter().take(5) {
            println!("{}: {}", entry.published.as_deref().unwrap_or("?"), entry.title);
            println!("  {}", entry.url);
        }
        Ok(())
    }
}

// line 33: compile-only (no_run)
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_33() {
    use finance_query::feeds::{self, FeedSource};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        // Aggregate multiple sources concurrently
        let news = feeds::fetch_all([
            FeedSource::FederalReserve,
            FeedSource::SecPressReleases,
            FeedSource::MarketWatch,
            FeedSource::Bloomberg,
            FeedSource::WsjMarkets,
        ]).await?;

        println!("Total entries (deduplicated): {}", news.len());
        for entry in news.iter().take(10) {
            println!("[{}] {}: {}", entry.source, entry.published.as_deref().unwrap_or("?"), entry.title);
        }
        Ok(())
    }
}

// line 59: compile-only (no_run)
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_59() {
    use finance_query::feeds::{self, FeedSource};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let custom = feeds::fetch(FeedSource::Custom(
            "https://example.com/feed.xml".to_string()
        )).await?;
        println!("{} entries", custom.len());
        Ok(())
    }
}

// line 186: compile-only (no_run)
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_186() {
    use finance_query::feeds::{self, FeedSource};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        // Stream the latest 10-K filings
        let filings = feeds::fetch(FeedSource::SecFilings("10-K".to_string())).await?;

        for f in &filings {
            println!("{}: {}", f.published.as_deref().unwrap_or("?"), f.title);
            println!("  {}", f.url);
        }
        Ok(())
    }
}
