// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/economic.md
#![allow(unused)]

// line 18: compile-only (no_run)
#[cfg(feature = "fred")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_18() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::ECONOMIC, [Provider::Fred])
            .build()
            .await?;
        let gdp = providers.economic("GDP");
        let series = gdp.series().await?;
        println!("{}: {} observations", series.series_id, series.observations.len());
        Ok(())
    }
}

// line 38: compile-only (no_run)
#[cfg(feature = "fred")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_38() {
        use finance_query::fred;

        fn main() -> Result<(), Box<dyn std::error::Error>> {
            fred::init(std::env::var("FRED_API_KEY")?)?;
            Ok(())
        }
}

// line 116: compile-only (no_run)
#[cfg(feature = "fred")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_116() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::ECONOMIC, [Provider::Fred])
            .build()
            .await?;

        let gdp = providers.economic("GDP");
        let series = gdp.series().await?;

        println!("Series:    {}", series.series_id);
        if let Some(title) = &series.title {
            println!("Title:     {}", title);
        }
        if let Some(units) = &series.units {
            println!("Units:     {}", units);
        }
        if let Some(freq) = &series.frequency {
            println!("Frequency: {}", freq);
        }
        println!("Observations: {}", series.observations.len());

        // Print the last 5 observations
        for obs in series.observations.iter().rev().take(5) {
            match obs.value {
                Some(v) => println!("{}: {:.1}", obs.date, v),
                None => println!("{}: N/A", obs.date),
            }
        }
        Ok(())
    }
}
