// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/kraken.md
#![allow(unused)]

// line 12: compile-only (no_run)
#[cfg(feature = "full")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_12() {
    use finance_query::{Capability, Fetch, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::CRYPTO, [Provider::Binance, Provider::Kraken, Provider::CoinGecko])
            .fetch(Fetch::Sequential)
            .build()
            .await?;
        Ok(())
    }
}

// line 33: compile-only (no_run)
#[cfg(feature = "kraken")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_33() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::CRYPTO, [Provider::Kraken])
            .build()
            .await?;

        let btc = providers.crypto("bitcoin");
        let quote = btc.quote("usd").await?;
        println!("BTC {:?}", quote.price);
        Ok(())
    }
}
