// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/worldbank.md
#![allow(unused)]

// line 14: compile-only (no_run)
#[cfg(feature = "worldbank")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_14() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::ECONOMIC, [Provider::WorldBank])
            .build()
            .await?;
        Ok(())
    }
}

// line 31: compile-only (no_run)
#[cfg(feature = "worldbank")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_31() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::ECONOMIC, [Provider::WorldBank])
            .build()
            .await?;

        let gdp = providers.economic("USA/NY.GDP.MKTP.CD").series().await?;

        println!("{}", gdp.title.unwrap_or_default());   // "GDP (current US$) — United States"
        for obs in &gdp.observations {
            println!("{} {:?}", obs.date, obs.value);    // "1960-01-01" Some(543300000000.0)
        }
        Ok(())
    }
}

// line 56: compile-only (no_run)
#[cfg(feature = "worldbank")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_56() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::ECONOMIC, [Provider::WorldBank])
            .build()
            .await?;

        // Equivalent to "WLD/SP.POP.TOTL" — world population
        let world_pop = providers.economic("SP.POP.TOTL").series().await?;
        Ok(())
    }
}

// line 103: compile-only (no_run)
#[cfg(feature = "full")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_103() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::ECONOMIC, [Provider::Fred, Provider::WorldBank])
            .build()
            .await?;
        Ok(())
    }
}
