// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/binance.md
#![allow(unused)]

// line 22: compile-only (no_run)
#[cfg(feature = "binance")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_22() {
    use finance_query::{Capability, Interval, Provider, Providers, TimeRange};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::CRYPTO, [Provider::Binance])
            .route(Capability::CHART, [Provider::Binance])
            .build()
            .await?;

        let btc = providers.crypto("bitcoin");
        let quote = btc.quote("usd").await?;
        println!("BTC {:?} ({:+.2?}%)", quote.price, quote.change_percent_24h);

        let chart = btc.chart("usd", Interval::OneHour, TimeRange::OneMonth).await?;
        println!("{} hourly candles", chart.candles.len());
        Ok(())
    }
}
