// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/cftc.md
#![allow(unused)]

// line 18: compile-only (no_run)
#[cfg(feature = "cftc")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_18() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::FUTURES, [Provider::Cftc, Provider::Yahoo])
            .build()
            .await?;

        let gold = providers.futures("GC=F");
        let cot = gold.commitments_of_traders().await?;

        println!("{} ({})", cot.market_and_exchange_name, cot.cftc_contract_market_code);
        for week in cot.observations.iter().rev().take(4) {
            println!(
                "{}: open interest {:?}, managed money long/short {:?}/{:?}",
                week.report_date, week.open_interest, week.managed_money_long, week.managed_money_short
            );
        }
        Ok(())
    }
}
