// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/commodities.md
#![allow(unused)]

// line 25: compile-only (no_run)
#[cfg(feature = "fmp")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_25() {
    use finance_query::{Capability, Interval, Provider, Providers, TimeRange};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::COMMODITIES, [Provider::Fmp])
            .build()
            .await?;
        let gold = providers.commodity("GCUSD");
        let quote = gold.quote().await?;
        let chart = gold.chart(Interval::OneDay, TimeRange::OneMonth).await?;
        let history = gold.history(TimeRange::OneMonth).await?;
        println!("{}: {:?} ({} candles)", quote.symbol, quote.price, chart.candles.len() + history.candles.len());
        Ok(())
    }
}

// line 49: compile-only (no_run)
#[cfg(feature = "fmp")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_49() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::COMMODITIES, [Provider::Fmp])
            .build()
            .await?;
        let gold = providers.commodity("GCUSD");
        let quote = gold.quote().await?;

        println!("Symbol: {}", quote.symbol);
        if let Some(name) = &quote.name {
            println!("Name: {}", name);
        }
        if let Some(price) = quote.price {
            println!("Price: {:.2}", price);
        }
        if let (Some(change), Some(pct)) = (quote.change, quote.change_percent) {
            println!("Change: {:+.2} ({:+.2}%)", change, pct);
        }
        Ok(())
    }
}

// line 79: compile-only (no_run)
#[cfg(feature = "fmp")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_79() {
    use finance_query::{Capability, Interval, Provider, Providers, TimeRange};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::COMMODITIES, [Provider::Fmp])
            .build()
            .await?;
        let crude = providers.commodity("CLUSD");
        let chart = crude.chart(Interval::OneDay, TimeRange::ThreeMonths).await?;

        println!("Symbol: {}", chart.symbol);
        println!("Candles: {}", chart.candles.len());
        for candle in chart.candles.iter().take(3) {
            println!("  t={} o={:.2} h={:.2} l={:.2} c={:.2}",
                candle.timestamp, candle.open, candle.high, candle.low, candle.close);
        }
        Ok(())
    }
}

// line 106: compile-only (no_run)
#[cfg(feature = "fmp")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_106() {
    use finance_query::{Capability, Provider, Providers, TimeRange};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::COMMODITIES, [Provider::Fmp])
            .build()
            .await?;
        let silver = providers.commodity("SIUSD");
        let history = silver.history(TimeRange::SixMonths).await?;

        println!("Symbol: {}", history.symbol);
        println!("Candles: {}", history.candles.len());
        Ok(())
    }
}

// line 129: compile-only (no_run)
#[cfg(feature = "risk")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_129() {
    use finance_query::indicators::Indicator;
    use finance_query::{Capability, Interval, Provider, Providers, TimeRange};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::COMMODITIES, [Provider::Fmp])
            .build()
            .await?;
        let gold = providers.commodity("GCUSD");

        let summary = gold.indicators(Interval::OneDay, TimeRange::ThreeMonths).await?;
        if let Some(rsi) = summary.rsi_14 {
            println!("RSI(14): {:.2}", rsi);
        }

        let rsi_21 = gold
            .indicator(Indicator::Rsi(21), Interval::OneDay, TimeRange::ThreeMonths)
            .await?;

        let risk = gold.risk(Interval::OneDay, TimeRange::OneYear).await?;
        println!("VaR 95%:      {:.2}%", risk.var_95 * 100.0);
        println!("Max Drawdown: {:.2}%", risk.max_drawdown * 100.0);
        Ok(())
    }
}
