// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/futures.md
#![allow(unused)]

// line 12: compile-only (no_run)
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_12() {
    use finance_query::{Interval, Providers, TimeRange};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder().build().await?;
        let contract = providers.futures("ES=F");
        let quote = contract.quote().await?;
        let chart = contract.chart(Interval::OneDay, TimeRange::OneMonth).await?;
        let history = contract.history(TimeRange::OneMonth).await?;
        println!("{}: {:?} ({} candles)", quote.symbol, quote.price, chart.candles.len() + history.candles.len());
        Ok(())
    }
}

// line 31: compile-only (no_run)
#[cfg(feature = "polygon")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_31() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::FUTURES, [Provider::Polygon, Provider::Yahoo])
            .build()
            .await?;
        let contract = providers.futures("ES");
        let quote = contract.quote().await?;
        println!("{}: {:?}", quote.symbol, quote.price);
        Ok(())
    }
}

// line 134: compile-only (no_run)
#[cfg(feature = "risk")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_134() {
    use finance_query::indicators::Indicator;
    use finance_query::{Interval, Providers, TimeRange};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder().build().await?;
        let contract = providers.futures("ES=F");

        let summary = contract
            .indicators(Interval::OneDay, TimeRange::ThreeMonths)
            .await?;
        if let Some(rsi) = summary.rsi_14 {
            println!("RSI(14): {:.2}", rsi);
        }

        let rsi_21 = contract
            .indicator(Indicator::Rsi(21), Interval::OneDay, TimeRange::ThreeMonths)
            .await?;

        let risk = contract.risk(Interval::OneDay, TimeRange::OneYear).await?;
        println!("VaR 95%:      {:.2}%", risk.var_95 * 100.0);
        println!("Max Drawdown: {:.2}%", risk.max_drawdown * 100.0);
        Ok(())
    }
}
