// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/defillama.md
#![allow(unused)]

// line 21: compile-only (no_run)
#[cfg(feature = "defi")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_21() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::CRYPTO, [Provider::DefiLlama])
            .build()
            .await?;

        let aave = providers.crypto("aave");
        let tvl = aave.tvl().await?;

        println!("{} — ${:?}", tvl.name.unwrap_or_default(), tvl.tvl);
        println!("1d {:?}%  7d {:?}%", tvl.change_1d_percent, tvl.change_7d_percent);
        for allocation in &tvl.tvl_by_chain {
            println!("  {}: ${:.0}", allocation.chain, allocation.tvl);
        }

        let history = aave.tvl_history().await?;   // oldest first
        Ok(())
    }
}

// line 64: compile-only (no_run)
#[cfg(feature = "defi")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_64() {
    use finance_query::defi;

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        // Chains ranked by total value locked
        for chain in defi::chains().await?.into_iter().take(10) {
            println!("{:<15} ${:?}", chain.name, chain.tvl);
        }

        // Stablecoins ranked by circulating supply
        for coin in defi::stablecoins().await?.into_iter().take(10) {
            println!(
                "{:<10} {:?} ({:?})",
                coin.symbol.unwrap_or_default(),
                coin.circulating,
                coin.peg_mechanism
            );
        }
        Ok(())
    }
}
