// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/coingecko.md
#![allow(unused)]

// line 13
#[cfg(feature = "crypto")]
#[rustfmt::skip]
#[test]
fn doc_block_line_13() {
    use finance_query::crypto;
}

// line 19: compile-only (no_run)
#[cfg(feature = "crypto")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_19() {
    use finance_query::crypto;

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        // Top 10 coins in USD
        let top = crypto::coins("usd", 10).await?;

        for coin in &top {
            let price   = coin.current_price.unwrap_or(0.0);
            let change  = coin.price_change_percentage_24h.unwrap_or(0.0);
            let rank    = coin.market_cap_rank.unwrap_or(0);
            println!("#{} {} ({}): ${:.2} ({:+.2}%)", rank, coin.name, coin.symbol, price, change);
        }
        Ok(())
    }
}

// line 46: compile-only (no_run)
#[cfg(feature = "crypto")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_46() {
    use finance_query::crypto;

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        // Look up by CoinGecko ID
        let btc = crypto::coin("bitcoin", "usd").await?;
        println!("Bitcoin: ${:.2}", btc.current_price.unwrap_or(0.0));

        let eth = crypto::coin("ethereum", "usd").await?;
        let mktcap = eth.market_cap.unwrap_or(0.0);
        println!("Ethereum market cap: ${:.2}B", mktcap / 1e9);
        Ok(())
    }
}
