// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/filings.md
#![allow(unused)]

// line 12: compile-only (no_run)
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_12() {
    use finance_query::{Providers, edgar};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        // EDGAR is keyless but SEC requires a contact email in the User-Agent.
        // Initialise it once per process (or set the EDGAR_EMAIL env var).
        edgar::init("you@example.com")?;

        let providers = Providers::builder().build().await?;
        let filings = providers.filings("AAPL");
        let result = filings.get().await?;

        for f in result.filings.iter().take(5) {
            println!(
                "{} {}: {}",
                f.filing_date.as_deref().unwrap_or("?"),
                f.filing_type.as_deref().unwrap_or("?"),
                f.filing_url.as_deref().unwrap_or("-")
            );
        }
        Ok(())
    }
}

// line 70: compile-only (no_run)
#[cfg(all(feature = "housetrades", feature = "senatetrades"))]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_70() {
    use finance_query::{Capability, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::FILINGS, [Provider::CongressTrades, Provider::Edgar])
            .build()
            .await?;

        let filings = providers.filings("AAPL");
        for trade in filings.congressional_trades().await? {
            println!(
                "{} {}: {} {} on {}",
                trade.office.as_deref().unwrap_or("?"),
                trade.last_name.as_deref().unwrap_or("?"),
                trade.trade_type.as_deref().unwrap_or("?"),
                trade.amount.as_deref().unwrap_or("?"),
                trade.transaction_date.as_deref().unwrap_or("?")
            );
        }
        Ok(())
    }
}

// line 119: compile-only (no_run)
#[cfg(feature = "secftd")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_119() {
    use finance_query::{Providers, edgar};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        edgar::init("you@example.com")?;

        let providers = Providers::builder().build().await?;
        let filings = providers.filings("AAPL");

        for row in filings.fails_to_deliver().await? {
            println!(
                "{}: {:?} shares of {:?}",
                row.date.as_deref().unwrap_or("?"),
                row.quantity,
                row.name
            );
        }
        Ok(())
    }
}
