// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/index.md
#![allow(unused)]

// line 67: compile-only (no_run)
#[cfg(feature = "full")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_67() {
    use finance_query::{Capability, Fetch, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            // Route quotes to Polygon first, Yahoo as fallback
            .route(Capability::QUOTE, [Provider::Polygon, Provider::Yahoo])
            // Route fundamentals to FMP first, Yahoo as fallback
            .route(Capability::FUNDAMENTALS, [Provider::Fmp, Provider::Yahoo])
            // Route corporate (news, recommendations) to Polygon only
            .route(Capability::CORPORATE, [Provider::Polygon])
            .fetch(Fetch::Sequential)
            .build()
            .await?;
        let ticker = providers.ticker("AAPL").build().await?;
        Ok(())
    }
}

// line 163: compile-only (no_run)
#[cfg(feature = "polygon")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_163() {
    use finance_query::{Capability, Fetch, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        // Sequential: try Polygon, then Yahoo if Polygon fails
        let providers = Providers::builder()
            .route(Capability::QUOTE, [Provider::Polygon, Provider::Yahoo])
            .fetch(Fetch::Sequential)
            .build()
            .await?;
        let ticker = providers.ticker("AAPL").build().await?;

        // Parallel: race Polygon against Yahoo, use whichever responds first
        let providers = Providers::builder()
            .route(Capability::QUOTE, [Provider::Polygon, Provider::Yahoo])
            .fetch(Fetch::Parallel)
            .build()
            .await?;
        let ticker = providers.ticker("AAPL").build().await?;
        Ok(())
    }
}

// line 218: compile-only (no_run)
#[cfg(feature = "full")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_218() {
    use finance_query::{Capability, Fetch, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::FOREX, [Provider::AlphaVantage])
            .route(Capability::ECONOMIC, [Provider::Fred])
            .route(Capability::CRYPTO, [Provider::CoinGecko])
            .fetch(Fetch::Sequential)
            .build()
            .await?;

        // All handles share the same provider connections
        let aapl  = providers.ticker("AAPL").logo().build().await?;   // → Ticker
        let pair  = providers.forex("USD", "EUR");                    // → ForexPair
        let btc   = providers.crypto("bitcoin");                      // → CryptoCoin
        let gdp   = providers.economic("REAL_GDP");                   // → EconomicIndicator
        let spy   = providers.index("SPY");                           // → Index
        let cl    = providers.futures("CL=F");                        // → FuturesContract
        let wheat = providers.commodity("WHEAT");                     // → Commodity
        let sec   = providers.filings("AAPL");                        // → Filings
        Ok(())
    }
}

// line 301: compile-only (no_run)
#[cfg(feature = "polygon")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_301() {
    use finance_query::{Capability, Fetch, Provider, Providers};

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let providers = Providers::builder()
            .route(Capability::QUOTE, [Provider::Polygon, Provider::Yahoo])
            .fetch(Fetch::Sequential)
            .build()
            .await?;
        let tickers = providers.tickers(["AAPL", "NVDA"]).build().await?;
        Ok(())
    }
}
