# Test your FastAPI endpoints

GET http://127.0.0.1:8000/v1/indices
Accept: application/json

###

GET http://127.0.0.1:8000/v1/actives
Accept: application/json

###

GET 127.0.0.1:8000/v1/gainers
Accept: application/json

###
GET 127.0.0.1:8000/v1/losers
Accept: application/json


###
http://127.0.0.1:8000/v1/news
Accept: application/json


###
http://127.0.0.1:8000/v1/quotes?symbols=AMZN
Accept: application/json


###
http://127.0.0.1:8000/v1/simple-quotes/?symbols=AMZN
Accept: application/json


###
http://127.0.0.1:8000/v1/similar-stocks/?symbol=AMZN
Accept: application/json


###
http://127.0.0.1:8000/v1/historical/?symbol=AMZN&time=YTD&interval=1d
Accept: application/json


###
http://127.0.0.1:8000/v1/indicators/?function=RSI&symbol=AMZN
Accept: application/json


###
http://127.0.0.1:8000/v1/analysis/?symbol=AMZN&time=YTD&interval=1d
Accept: application/json