// Code generated by `cargo soothfast sdk gen`. DO NOT EDIT.
/** finance-query — generated client for Finance Query v2. */

export * from "./client.js";
export * from "./models.js";
export {
  ApiError,
  AsyncPager,
  BadRequestError,
  NotFoundError,
  RateLimitError,
  ServerError,
  ServiceUnavailableError,
  Transport,
  type ApiErrorInit,
  type BaseUrl,
  type ClientOptions,
  type Page,
  type PageInfo,
  type RequestOptions,
  type TransportOptions,
} from "./runtime.js";
export {
  EmbeddedServer,
  stopEmbeddedServers,
  type EmbedConfig,
  type StartOptions,
} from "./server.js";

/** The version this client was generated for. */
export const VERSION = "2.8.0";
