// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use pyo3::prelude::*;

/// The runtime an exported `async fn` is polled inside.
fn runtime() -> &'static ::tokio::runtime::Runtime {
    static RUNTIME: ::std::sync::OnceLock<::tokio::runtime::Runtime> =
        ::std::sync::OnceLock::new();
    RUNTIME.get_or_init(|| {
        ::tokio::runtime::Runtime::new()
            .unwrap_or_else(|e| panic!("start the binding runtime: {e}"))
    })
}

/// A future polled inside [`runtime`]'s context.
///
/// The guard is taken per poll rather than held across awaits: it restores a
/// thread-local on drop, and a suspended future would leave that thread
/// carrying a context it never entered.
///
/// The future never sees pyo3's waker, which takes the GIL the polling
/// thread holds: a library waking from under one of its own locks would
/// deadlock against it. It is polled with a waker that only signals
/// `Relay::notify`, and a runtime task relays each signal to pyo3's waker
/// from a context holding no lock at all.
struct OnRuntime<F> {
    inner: F,
    relay: Option<::std::sync::Arc<Relay>>,
}

impl<F> OnRuntime<F> {
    fn new(inner: F) -> Self {
        OnRuntime { inner, relay: None }
    }
}

#[derive(Default)]
struct Relay {
    notify: ::tokio::sync::Notify,
    target: ::std::sync::Mutex<Option<::std::task::Waker>>,
    done: ::std::sync::atomic::AtomicBool,
}

impl ::std::task::Wake for Relay {
    fn wake(self: ::std::sync::Arc<Self>) {
        self.notify.notify_one();
    }

    fn wake_by_ref(self: &::std::sync::Arc<Self>) {
        self.notify.notify_one();
    }
}

impl Relay {
    fn start() -> ::std::sync::Arc<Relay> {
        let relay = ::std::sync::Arc::new(Relay::default());
        let task = ::std::sync::Arc::clone(&relay);
        runtime().spawn(async move {
            loop {
                task.notify.notified().await;
                if task.done.load(::std::sync::atomic::Ordering::Acquire) {
                    break;
                }
                let target = task.target.lock().unwrap_or_else(|e| e.into_inner()).clone();
                if let Some(waker) = target {
                    waker.wake();
                }
            }
        });
        relay
    }
}

impl<F> Drop for OnRuntime<F> {
    fn drop(&mut self) {
        if let Some(relay) = &self.relay {
            relay.done.store(true, ::std::sync::atomic::Ordering::Release);
            relay.notify.notify_one();
        }
    }
}

impl<F: ::std::future::Future> ::std::future::Future for OnRuntime<F> {
    type Output = F::Output;

    fn poll(
        self: ::std::pin::Pin<&mut Self>,
        cx: &mut ::std::task::Context<'_>,
    ) -> ::std::task::Poll<F::Output> {
        // `inner` is never moved out of the wrapper, and `relay` is `Unpin`.
        let this = unsafe { self.get_unchecked_mut() };
        let _guard = runtime().enter();
        let relay = this.relay.get_or_insert_with(Relay::start);
        *relay.target.lock().unwrap_or_else(|e| e.into_inner()) = Some(cx.waker().clone());
        let waker = ::std::task::Waker::from(::std::sync::Arc::clone(relay));
        let mut relayed = ::std::task::Context::from_waker(&waker);
        unsafe { ::std::pin::Pin::new_unchecked(&mut this.inner) }.poll(&mut relayed)
    }
}

/// An owned `f64` sequence. `memoryview(x)` and `numpy.asarray(x)` read
/// it without copying; `x.tolist()` copies it into a plain list.
#[pyclass(name = "F64Array")]
pub struct F64Array(Vec<f64>);

impl F64Array {
    fn new(values: Vec<f64>) -> Self {
        F64Array(values)
    }
}

#[pymethods]
impl F64Array {
    fn __len__(&self) -> usize {
        self.0.len()
    }

    fn __getitem__(&self, index: isize) -> ::pyo3::PyResult<f64> {
        let at = match index < 0 {
            true => index + self.0.len() as isize,
            false => index,
        };
        usize::try_from(at)
            .ok()
            .and_then(|at| self.0.get(at))
            .copied()
            .ok_or_else(|| ::pyo3::exceptions::PyIndexError::new_err("index out of range"))
    }

    fn __iter__<'py>(
        &self,
        py: ::pyo3::Python<'py>,
    ) -> ::pyo3::PyResult<::pyo3::Bound<'py, ::pyo3::PyAny>> {
        use ::pyo3::types::PyAnyMethods;
        Ok(::pyo3::types::PyList::new(py, &self.0)?.try_iter()?.into_any())
    }

    fn __repr__(&self) -> String {
        format!("F64Array({:?})", self.0)
    }

    /// The same values as a plain Python list.
    fn tolist(&self) -> Vec<f64> {
        self.0.clone()
    }

    unsafe fn __getbuffer__(
        slf: ::pyo3::Bound<'_, Self>,
        view: *mut ::pyo3::ffi::Py_buffer,
        flags: ::std::os::raw::c_int,
    ) -> ::pyo3::PyResult<()> {
        if view.is_null() {
            return Err(::pyo3::exceptions::PyBufferError::new_err("view is null"));
        }
        if (flags & ::pyo3::ffi::PyBUF_WRITABLE) == ::pyo3::ffi::PyBUF_WRITABLE {
            return Err(::pyo3::exceptions::PyBufferError::new_err(
                "F64Array is read-only",
            ));
        }
        let size = ::std::mem::size_of::<f64>() as isize;
        let (buf, count) = {
            let values = &slf.borrow().0;
            (values.as_ptr() as *mut ::std::ffi::c_void, values.len() as isize)
        };
        let meta = Box::into_raw(Box::new([count, size]));
        unsafe {
            (*view).obj = slf.into_ptr();
            (*view).buf = buf;
            (*view).len = count * size;
            (*view).readonly = 1;
            (*view).itemsize = size;
            (*view).ndim = 1;
            (*view).format = match (flags & ::pyo3::ffi::PyBUF_FORMAT) == ::pyo3::ffi::PyBUF_FORMAT
            {
                true => c"d".as_ptr() as *mut ::std::os::raw::c_char,
                false => ::std::ptr::null_mut(),
            };
            (*view).shape = match (flags & ::pyo3::ffi::PyBUF_ND) == ::pyo3::ffi::PyBUF_ND {
                true => meta as *mut isize,
                false => ::std::ptr::null_mut(),
            };
            (*view).strides = match (flags & ::pyo3::ffi::PyBUF_STRIDES)
                == ::pyo3::ffi::PyBUF_STRIDES
            {
                true => (meta as *mut isize).add(1),
                false => ::std::ptr::null_mut(),
            };
            (*view).suboffsets = ::std::ptr::null_mut();
            (*view).internal = meta as *mut ::std::ffi::c_void;
        }
        Ok(())
    }

    unsafe fn __releasebuffer__(&self, view: *mut ::pyo3::ffi::Py_buffer) {
        // Paired with the `Box::into_raw` every filled view carries out.
        unsafe { drop(Box::from_raw((*view).internal as *mut [isize; 2])) };
    }
}

/// An owned `i64` sequence. `memoryview(x)` and `numpy.asarray(x)` read
/// it without copying; `x.tolist()` copies it into a plain list.
#[pyclass(name = "I64Array")]
pub struct I64Array(Vec<i64>);

impl I64Array {
    fn new(values: Vec<i64>) -> Self {
        I64Array(values)
    }
}

#[pymethods]
impl I64Array {
    fn __len__(&self) -> usize {
        self.0.len()
    }

    fn __getitem__(&self, index: isize) -> ::pyo3::PyResult<i64> {
        let at = match index < 0 {
            true => index + self.0.len() as isize,
            false => index,
        };
        usize::try_from(at)
            .ok()
            .and_then(|at| self.0.get(at))
            .copied()
            .ok_or_else(|| ::pyo3::exceptions::PyIndexError::new_err("index out of range"))
    }

    fn __iter__<'py>(
        &self,
        py: ::pyo3::Python<'py>,
    ) -> ::pyo3::PyResult<::pyo3::Bound<'py, ::pyo3::PyAny>> {
        use ::pyo3::types::PyAnyMethods;
        Ok(::pyo3::types::PyList::new(py, &self.0)?.try_iter()?.into_any())
    }

    fn __repr__(&self) -> String {
        format!("I64Array({:?})", self.0)
    }

    /// The same values as a plain Python list.
    fn tolist(&self) -> Vec<i64> {
        self.0.clone()
    }

    unsafe fn __getbuffer__(
        slf: ::pyo3::Bound<'_, Self>,
        view: *mut ::pyo3::ffi::Py_buffer,
        flags: ::std::os::raw::c_int,
    ) -> ::pyo3::PyResult<()> {
        if view.is_null() {
            return Err(::pyo3::exceptions::PyBufferError::new_err("view is null"));
        }
        if (flags & ::pyo3::ffi::PyBUF_WRITABLE) == ::pyo3::ffi::PyBUF_WRITABLE {
            return Err(::pyo3::exceptions::PyBufferError::new_err(
                "I64Array is read-only",
            ));
        }
        let size = ::std::mem::size_of::<i64>() as isize;
        let (buf, count) = {
            let values = &slf.borrow().0;
            (values.as_ptr() as *mut ::std::ffi::c_void, values.len() as isize)
        };
        let meta = Box::into_raw(Box::new([count, size]));
        unsafe {
            (*view).obj = slf.into_ptr();
            (*view).buf = buf;
            (*view).len = count * size;
            (*view).readonly = 1;
            (*view).itemsize = size;
            (*view).ndim = 1;
            (*view).format = match (flags & ::pyo3::ffi::PyBUF_FORMAT) == ::pyo3::ffi::PyBUF_FORMAT
            {
                true => c"q".as_ptr() as *mut ::std::os::raw::c_char,
                false => ::std::ptr::null_mut(),
            };
            (*view).shape = match (flags & ::pyo3::ffi::PyBUF_ND) == ::pyo3::ffi::PyBUF_ND {
                true => meta as *mut isize,
                false => ::std::ptr::null_mut(),
            };
            (*view).strides = match (flags & ::pyo3::ffi::PyBUF_STRIDES)
                == ::pyo3::ffi::PyBUF_STRIDES
            {
                true => (meta as *mut isize).add(1),
                false => ::std::ptr::null_mut(),
            };
            (*view).suboffsets = ::std::ptr::null_mut();
            (*view).internal = meta as *mut ::std::ffi::c_void;
        }
        Ok(())
    }

    unsafe fn __releasebuffer__(&self, view: *mut ::pyo3::ffi::Py_buffer) {
        // Paired with the `Box::into_raw` every filled view carries out.
        unsafe { drop(Box::from_raw((*view).internal as *mut [isize; 2])) };
    }
}

/// A sequence of `Candle` read from a field. Indexing builds one handle;
/// `x.tolist()` builds them all; a column getter reads one field of every
/// element at once.
#[pyclass(name = "CandleSeq")]
pub struct CandleSeq(Vec<::finance_query::Candle>);

impl CandleSeq {
    fn new(values: Vec<::finance_query::Candle>) -> Self {
        CandleSeq(values)
    }
}

#[pymethods]
impl CandleSeq {
    fn __len__(&self) -> usize {
        self.0.len()
    }

    fn __getitem__(&self, index: isize) -> ::pyo3::PyResult<Candle> {
        let at = match index < 0 {
            true => index + self.0.len() as isize,
            false => index,
        };
        usize::try_from(at)
            .ok()
            .and_then(|at| self.0.get(at))
            .cloned()
            .map(Candle)
            .ok_or_else(|| ::pyo3::exceptions::PyIndexError::new_err("index out of range"))
    }

    fn __iter__<'py>(
        &self,
        py: ::pyo3::Python<'py>,
    ) -> ::pyo3::PyResult<::pyo3::Bound<'py, ::pyo3::PyAny>> {
        use ::pyo3::types::PyAnyMethods;
        Ok(::pyo3::types::PyList::new(py, self.tolist())?.try_iter()?.into_any())
    }

    fn __repr__(&self) -> String {
        format!("CandleSeq(len={})", self.0.len())
    }

    /// Every element as a handle, in a plain list.
    fn tolist(&self) -> Vec<Candle> {
        self.0.iter().cloned().map(Candle).collect()
    }

    /// Timestamp (Unix)
    #[getter]
    fn timestamp(&self) -> I64Array {
        I64Array::new(self.0.iter().map(|v| v.timestamp).collect())
    }

    /// Open price
    #[getter]
    fn open(&self) -> F64Array {
        F64Array::new(self.0.iter().map(|v| v.open).collect())
    }

    /// High price
    #[getter]
    fn high(&self) -> F64Array {
        F64Array::new(self.0.iter().map(|v| v.high).collect())
    }

    /// Low price
    #[getter]
    fn low(&self) -> F64Array {
        F64Array::new(self.0.iter().map(|v| v.low).collect())
    }

    /// Close price
    #[getter]
    fn close(&self) -> F64Array {
        F64Array::new(self.0.iter().map(|v| v.close).collect())
    }

    /// Volume
    #[getter]
    fn volume(&self) -> I64Array {
        I64Array::new(self.0.iter().map(|v| v.volume).collect())
    }

    /// Adjusted close (if available)
    #[getter]
    fn adj_close(&self) -> Vec<Option<f64>> {
        self.0.iter().map(|v| v.adj_close).collect()
    }
}

/// A sequence of `SimilarSymbol` read from a field. Indexing builds one handle;
/// `x.tolist()` builds them all; a column getter reads one field of every
/// element at once.
#[pyclass(name = "SimilarSymbolSeq")]
pub struct SimilarSymbolSeq(Vec<::finance_query::SimilarSymbol>);

impl SimilarSymbolSeq {
    fn new(values: Vec<::finance_query::SimilarSymbol>) -> Self {
        SimilarSymbolSeq(values)
    }
}

#[pymethods]
impl SimilarSymbolSeq {
    fn __len__(&self) -> usize {
        self.0.len()
    }

    fn __getitem__(&self, index: isize) -> ::pyo3::PyResult<SimilarSymbol> {
        let at = match index < 0 {
            true => index + self.0.len() as isize,
            false => index,
        };
        usize::try_from(at)
            .ok()
            .and_then(|at| self.0.get(at))
            .cloned()
            .map(SimilarSymbol)
            .ok_or_else(|| ::pyo3::exceptions::PyIndexError::new_err("index out of range"))
    }

    fn __iter__<'py>(
        &self,
        py: ::pyo3::Python<'py>,
    ) -> ::pyo3::PyResult<::pyo3::Bound<'py, ::pyo3::PyAny>> {
        use ::pyo3::types::PyAnyMethods;
        Ok(::pyo3::types::PyList::new(py, self.tolist())?.try_iter()?.into_any())
    }

    fn __repr__(&self) -> String {
        format!("SimilarSymbolSeq(len={})", self.0.len())
    }

    /// Every element as a handle, in a plain list.
    fn tolist(&self) -> Vec<SimilarSymbol> {
        self.0.iter().cloned().map(SimilarSymbol).collect()
    }

    /// Stock symbol
    #[getter]
    fn symbol(&self) -> Vec<String> {
        self.0.iter().map(|v| v.symbol.clone()).collect()
    }

    /// Recommendation score (higher = more similar)
    #[getter]
    fn score(&self) -> F64Array {
        F64Array::new(self.0.iter().map(|v| v.score).collect())
    }
}

::pyo3::create_exception!(finance_query, Error, ::pyo3::exceptions::PyException, "Base of every error finance-query raises.");
::pyo3::create_exception!(finance_query, BacktestError, Error, "Backtest-specific errors");
::pyo3::create_exception!(finance_query, InvalidParameter, BacktestError, "Invalid configuration parameter");
::pyo3::create_exception!(finance_query, InsufficientData, BacktestError, "Insufficient data for backtest");
::pyo3::create_exception!(finance_query, StrategyError, BacktestError, "Strategy error during execution");
::pyo3::create_exception!(finance_query, IndicatorError, BacktestError, "Indicator calculation failed");
::pyo3::create_exception!(finance_query, ChartError, BacktestError, "Chart data fetch failed");
::pyo3::create_exception!(finance_query, PositionError, BacktestError, "Position management error");
::pyo3::create_exception!(finance_query, FinanceError, Error, "Main error type for the library");
::pyo3::create_exception!(finance_query, AuthenticationFailed, FinanceError, "Authentication failed (Yahoo Finance, SEC EDGAR, etc.)");
::pyo3::create_exception!(finance_query, ProviderNotConfigured, FinanceError, "A provider is compiled in but has no credentials configured.");
::pyo3::create_exception!(finance_query, SymbolNotFound, FinanceError, "The requested symbol was not found");
::pyo3::create_exception!(finance_query, RateLimited, FinanceError, "Rate limit exceeded");
::pyo3::create_exception!(finance_query, HttpError, FinanceError, "HTTP request error");
::pyo3::create_exception!(finance_query, NetworkError, FinanceError, "Transport-level failure whose source is withheld.");
::pyo3::create_exception!(finance_query, JsonParseError, FinanceError, "Failed to parse JSON response");
::pyo3::create_exception!(finance_query, ResponseStructureError, FinanceError, "Response structure error - missing or malformed fields");
::pyo3::create_exception!(finance_query, InvalidParameterError, FinanceError, "Invalid parameter provided");
::pyo3::create_exception!(finance_query, Timeout, FinanceError, "Network timeout");
::pyo3::create_exception!(finance_query, ServerError, FinanceError, "Server error (5xx status codes)");
::pyo3::create_exception!(finance_query, UnexpectedResponse, FinanceError, "Unexpected API response");
::pyo3::create_exception!(finance_query, InternalError, FinanceError, "Internal error");
::pyo3::create_exception!(finance_query, ApiError, FinanceError, "General API error");
::pyo3::create_exception!(finance_query, RuntimeError, FinanceError, "Tokio runtime error");
::pyo3::create_exception!(finance_query, IndicatorErrorError, FinanceError, "Indicator calculation error");
::pyo3::create_exception!(finance_query, ExternalApiError, FinanceError, "Error from an external (non-Yahoo) data API");
::pyo3::create_exception!(finance_query, MacroDataError, FinanceError, "Error fetching or parsing macro-economic data (FRED, Treasury, BLS)");
::pyo3::create_exception!(finance_query, FeedParseError, FinanceError, "Error parsing an RSS/Atom feed");
::pyo3::create_exception!(finance_query, NotSupported, FinanceError, "The requested operation is not supported by this provider.");
::pyo3::create_exception!(finance_query, NoProviderAvailable, FinanceError, "No configured provider supports this operation or all providers failed.");
::pyo3::create_exception!(finance_query, ProviderNotRegistered, FinanceError, "A route names a provider with no adapter registered for it.");
::pyo3::create_exception!(finance_query, TranslationError, FinanceError, "Translation backend failure (model download, load, or inference)");

struct BindErrorfinancequeryerrorFinanceError(::finance_query::FinanceError);

impl ::std::convert::From<BindErrorfinancequeryerrorFinanceError> for ::pyo3::PyErr {
    #[allow(unreachable_patterns)]
    fn from(err: BindErrorfinancequeryerrorFinanceError) -> ::pyo3::PyErr {
        let message = ::std::string::ToString::to_string(&err.0);
        match err.0 {
            ::finance_query::FinanceError::AuthenticationFailed { context, .. } => {
                let e = AuthenticationFailed::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("context", context);
                });
                e
            }
            ::finance_query::FinanceError::ProviderNotConfigured { provider, env_var, .. } => {
                let e = ProviderNotConfigured::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("provider", provider);
                    let _ = value.setattr("env_var", env_var);
                });
                e
            }
            ::finance_query::FinanceError::SymbolNotFound { symbol, context, .. } => {
                let e = SymbolNotFound::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("symbol", symbol);
                    let _ = value.setattr("context", context);
                });
                e
            }
            ::finance_query::FinanceError::RateLimited { retry_after, .. } => {
                let e = RateLimited::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("retry_after", retry_after);
                });
                e
            }
            ::finance_query::FinanceError::HttpError(..) => HttpError::new_err(message),
            ::finance_query::FinanceError::NetworkError { api, .. } => {
                let e = NetworkError::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("api", api);
                });
                e
            }
            ::finance_query::FinanceError::JsonParseError(..) => JsonParseError::new_err(message),
            ::finance_query::FinanceError::ResponseStructureError { field, context, .. } => {
                let e = ResponseStructureError::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("field", field);
                    let _ = value.setattr("context", context);
                });
                e
            }
            ::finance_query::FinanceError::InvalidParameter { param, reason, .. } => {
                let e = InvalidParameterError::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("param", param);
                    let _ = value.setattr("reason", reason);
                });
                e
            }
            ::finance_query::FinanceError::Timeout { timeout_ms, .. } => {
                let e = Timeout::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("timeout_ms", timeout_ms);
                });
                e
            }
            ::finance_query::FinanceError::ServerError { status, context, .. } => {
                let e = ServerError::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("status", status);
                    let _ = value.setattr("context", context);
                });
                e
            }
            ::finance_query::FinanceError::UnexpectedResponse(..) => UnexpectedResponse::new_err(message),
            ::finance_query::FinanceError::InternalError(..) => InternalError::new_err(message),
            ::finance_query::FinanceError::ApiError(..) => ApiError::new_err(message),
            ::finance_query::FinanceError::RuntimeError(..) => RuntimeError::new_err(message),
            ::finance_query::FinanceError::IndicatorError(..) => IndicatorErrorError::new_err(message),
            ::finance_query::FinanceError::ExternalApiError { api, status, .. } => {
                let e = ExternalApiError::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("api", api);
                    let _ = value.setattr("status", status);
                });
                e
            }
            ::finance_query::FinanceError::MacroDataError { provider, context, .. } => {
                let e = MacroDataError::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("provider", provider);
                    let _ = value.setattr("context", context);
                });
                e
            }
            ::finance_query::FinanceError::FeedParseError { url, context, .. } => {
                let e = FeedParseError::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("url", url);
                    let _ = value.setattr("context", context);
                });
                e
            }
            ::finance_query::FinanceError::NotSupported { .. } => NotSupported::new_err(message),
            ::finance_query::FinanceError::NoProviderAvailable { .. } => NoProviderAvailable::new_err(message),
            ::finance_query::FinanceError::ProviderNotRegistered { .. } => ProviderNotRegistered::new_err(message),
            ::finance_query::FinanceError::TranslationError { context, .. } => {
                let e = TranslationError::new_err(message);
                ::pyo3::Python::attach(|py| {
                    let value = e.value(py);
                    let _ = value.setattr("context", context);
                });
                e
            }
            _ => FinanceError::new_err(message),
        }
    }
}

/// Chart intervals
#[pyclass(name = "Interval", eq, eq_int, from_py_object)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Interval {
    OneMinute,
    TwoMinutes,
    FiveMinutes,
    FifteenMinutes,
    ThirtyMinutes,
    OneHour,
    NinetyMinutes,
    OneDay,
    FiveDays,
    OneWeek,
    OneMonth,
    ThreeMonths,
}

impl ::std::convert::From<::finance_query::Interval> for Interval {
    #[allow(unreachable_patterns)]
    fn from(value: ::finance_query::Interval) -> Self {
        match value {
            ::finance_query::Interval::OneMinute => Interval::OneMinute,
            ::finance_query::Interval::TwoMinutes => Interval::TwoMinutes,
            ::finance_query::Interval::FiveMinutes => Interval::FiveMinutes,
            ::finance_query::Interval::FifteenMinutes => Interval::FifteenMinutes,
            ::finance_query::Interval::ThirtyMinutes => Interval::ThirtyMinutes,
            ::finance_query::Interval::OneHour => Interval::OneHour,
            ::finance_query::Interval::NinetyMinutes => Interval::NinetyMinutes,
            ::finance_query::Interval::OneDay => Interval::OneDay,
            ::finance_query::Interval::FiveDays => Interval::FiveDays,
            ::finance_query::Interval::OneWeek => Interval::OneWeek,
            ::finance_query::Interval::OneMonth => Interval::OneMonth,
            ::finance_query::Interval::ThreeMonths => Interval::ThreeMonths,
            _ => ::std::unreachable!("::finance_query::Interval gained a variant this binding was not generated for"),
        }
    }
}

// A mirrored enum has no derived `Clone`; a field getter converts through
// this one instead of cloning an owned copy just to consume it.
impl ::std::convert::From<&::finance_query::Interval> for Interval {
    #[allow(unreachable_patterns)]
    fn from(value: &::finance_query::Interval) -> Self {
        match value {
            ::finance_query::Interval::OneMinute => Interval::OneMinute,
            ::finance_query::Interval::TwoMinutes => Interval::TwoMinutes,
            ::finance_query::Interval::FiveMinutes => Interval::FiveMinutes,
            ::finance_query::Interval::FifteenMinutes => Interval::FifteenMinutes,
            ::finance_query::Interval::ThirtyMinutes => Interval::ThirtyMinutes,
            ::finance_query::Interval::OneHour => Interval::OneHour,
            ::finance_query::Interval::NinetyMinutes => Interval::NinetyMinutes,
            ::finance_query::Interval::OneDay => Interval::OneDay,
            ::finance_query::Interval::FiveDays => Interval::FiveDays,
            ::finance_query::Interval::OneWeek => Interval::OneWeek,
            ::finance_query::Interval::OneMonth => Interval::OneMonth,
            ::finance_query::Interval::ThreeMonths => Interval::ThreeMonths,
            _ => ::std::unreachable!("::finance_query::Interval gained a variant this binding was not generated for"),
        }
    }
}

impl ::std::convert::From<Interval> for ::finance_query::Interval {
    fn from(value: Interval) -> Self {
        match value {
            Interval::OneMinute => ::finance_query::Interval::OneMinute,
            Interval::TwoMinutes => ::finance_query::Interval::TwoMinutes,
            Interval::FiveMinutes => ::finance_query::Interval::FiveMinutes,
            Interval::FifteenMinutes => ::finance_query::Interval::FifteenMinutes,
            Interval::ThirtyMinutes => ::finance_query::Interval::ThirtyMinutes,
            Interval::OneHour => ::finance_query::Interval::OneHour,
            Interval::NinetyMinutes => ::finance_query::Interval::NinetyMinutes,
            Interval::OneDay => ::finance_query::Interval::OneDay,
            Interval::FiveDays => ::finance_query::Interval::FiveDays,
            Interval::OneWeek => ::finance_query::Interval::OneWeek,
            Interval::OneMonth => ::finance_query::Interval::OneMonth,
            Interval::ThreeMonths => ::finance_query::Interval::ThreeMonths,
        }
    }
}

/// Time ranges for chart data
#[pyclass(name = "TimeRange", eq, eq_int, from_py_object)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TimeRange {
    OneDay,
    FiveDays,
    OneMonth,
    ThreeMonths,
    SixMonths,
    OneYear,
    TwoYears,
    FiveYears,
    TenYears,
    YearToDate,
    Max,
}

impl ::std::convert::From<::finance_query::TimeRange> for TimeRange {
    #[allow(unreachable_patterns)]
    fn from(value: ::finance_query::TimeRange) -> Self {
        match value {
            ::finance_query::TimeRange::OneDay => TimeRange::OneDay,
            ::finance_query::TimeRange::FiveDays => TimeRange::FiveDays,
            ::finance_query::TimeRange::OneMonth => TimeRange::OneMonth,
            ::finance_query::TimeRange::ThreeMonths => TimeRange::ThreeMonths,
            ::finance_query::TimeRange::SixMonths => TimeRange::SixMonths,
            ::finance_query::TimeRange::OneYear => TimeRange::OneYear,
            ::finance_query::TimeRange::TwoYears => TimeRange::TwoYears,
            ::finance_query::TimeRange::FiveYears => TimeRange::FiveYears,
            ::finance_query::TimeRange::TenYears => TimeRange::TenYears,
            ::finance_query::TimeRange::YearToDate => TimeRange::YearToDate,
            ::finance_query::TimeRange::Max => TimeRange::Max,
            _ => ::std::unreachable!("::finance_query::TimeRange gained a variant this binding was not generated for"),
        }
    }
}

// A mirrored enum has no derived `Clone`; a field getter converts through
// this one instead of cloning an owned copy just to consume it.
impl ::std::convert::From<&::finance_query::TimeRange> for TimeRange {
    #[allow(unreachable_patterns)]
    fn from(value: &::finance_query::TimeRange) -> Self {
        match value {
            ::finance_query::TimeRange::OneDay => TimeRange::OneDay,
            ::finance_query::TimeRange::FiveDays => TimeRange::FiveDays,
            ::finance_query::TimeRange::OneMonth => TimeRange::OneMonth,
            ::finance_query::TimeRange::ThreeMonths => TimeRange::ThreeMonths,
            ::finance_query::TimeRange::SixMonths => TimeRange::SixMonths,
            ::finance_query::TimeRange::OneYear => TimeRange::OneYear,
            ::finance_query::TimeRange::TwoYears => TimeRange::TwoYears,
            ::finance_query::TimeRange::FiveYears => TimeRange::FiveYears,
            ::finance_query::TimeRange::TenYears => TimeRange::TenYears,
            ::finance_query::TimeRange::YearToDate => TimeRange::YearToDate,
            ::finance_query::TimeRange::Max => TimeRange::Max,
            _ => ::std::unreachable!("::finance_query::TimeRange gained a variant this binding was not generated for"),
        }
    }
}

impl ::std::convert::From<TimeRange> for ::finance_query::TimeRange {
    fn from(value: TimeRange) -> Self {
        match value {
            TimeRange::OneDay => ::finance_query::TimeRange::OneDay,
            TimeRange::FiveDays => ::finance_query::TimeRange::FiveDays,
            TimeRange::OneMonth => ::finance_query::TimeRange::OneMonth,
            TimeRange::ThreeMonths => ::finance_query::TimeRange::ThreeMonths,
            TimeRange::SixMonths => ::finance_query::TimeRange::SixMonths,
            TimeRange::OneYear => ::finance_query::TimeRange::OneYear,
            TimeRange::TwoYears => ::finance_query::TimeRange::TwoYears,
            TimeRange::FiveYears => ::finance_query::TimeRange::FiveYears,
            TimeRange::TenYears => ::finance_query::TimeRange::TenYears,
            TimeRange::YearToDate => ::finance_query::TimeRange::YearToDate,
            TimeRange::Max => ::finance_query::TimeRange::Max,
        }
    }
}

/// A single OHLCV candle/bar
#[pyclass(name = "Candle")]
pub struct Candle(::finance_query::Candle);

#[pymethods]
impl Candle {
    /// Timestamp (Unix)
    #[getter]
    fn timestamp(&self) -> i64 {
        self.0.timestamp.clone()
    }

    #[setter]
    fn set_timestamp(&mut self, value: i64) {
        self.0.timestamp = value;
    }

    /// Open price
    #[getter]
    fn open(&self) -> f64 {
        self.0.open.clone()
    }

    #[setter]
    fn set_open(&mut self, value: f64) {
        self.0.open = value;
    }

    /// High price
    #[getter]
    fn high(&self) -> f64 {
        self.0.high.clone()
    }

    #[setter]
    fn set_high(&mut self, value: f64) {
        self.0.high = value;
    }

    /// Low price
    #[getter]
    fn low(&self) -> f64 {
        self.0.low.clone()
    }

    #[setter]
    fn set_low(&mut self, value: f64) {
        self.0.low = value;
    }

    /// Close price
    #[getter]
    fn close(&self) -> f64 {
        self.0.close.clone()
    }

    #[setter]
    fn set_close(&mut self, value: f64) {
        self.0.close = value;
    }

    /// Volume
    #[getter]
    fn volume(&self) -> i64 {
        self.0.volume.clone()
    }

    #[setter]
    fn set_volume(&mut self, value: i64) {
        self.0.volume = value;
    }

    /// Adjusted close (if available)
    #[getter]
    fn adj_close(&self) -> Option<f64> {
        self.0.adj_close.clone()
    }

    #[setter]
    fn set_adj_close(&mut self, value: Option<f64>) {
        self.0.adj_close = value;
    }

    /// Which data provider served this data (e.g., "yahoo", "polygon").
    #[getter]
    fn provider_id(&self) -> Option<Provider> {
        self.0.provider_id.clone().map(Provider)
    }

    fn __repr__(&self) -> String {
        format!("Candle(timestamp={:?}, open={:?}, high={:?}, low={:?}, close={:?}, volume={:?}, adj_close={:?})", self.0.timestamp, self.0.open, self.0.high, self.0.low, self.0.close, self.0.volume, self.0.adj_close)
    }
}

/// Fully typed chart data
#[pyclass(name = "Chart")]
pub struct Chart(::finance_query::Chart);

#[pymethods]
impl Chart {
    /// Stock symbol
    #[getter]
    fn symbol(&self) -> String {
        self.0.symbol.clone()
    }

    #[setter]
    fn set_symbol(&mut self, value: String) {
        self.0.symbol = value;
    }

    /// Chart metadata (exchange, currency, 52-week range, etc.)
    #[getter]
    fn meta(&self) -> ChartMeta {
        ChartMeta(self.0.meta.clone())
    }

    /// OHLCV candles/bars
    #[getter]
    fn candles(&self) -> CandleSeq {
        CandleSeq::new(self.0.candles.clone())
    }

    /// Time interval used (e.g., `Interval::OneDay`)
    #[getter]
    fn interval(&self) -> Option<Interval> {
        self.0.interval.clone().map(::std::convert::Into::into)
    }

    #[setter]
    fn set_interval(&mut self, value: Option<Interval>) {
        self.0.interval = value.map(::std::convert::Into::into);
    }

    /// Time range used (e.g., `TimeRange::OneYear`)
    #[getter]
    fn range(&self) -> Option<TimeRange> {
        self.0.range.clone().map(::std::convert::Into::into)
    }

    #[setter]
    fn set_range(&mut self, value: Option<TimeRange>) {
        self.0.range = value.map(::std::convert::Into::into);
    }

    /// Which data provider served this data (e.g., "yahoo", "polygon").
    #[getter]
    fn provider_id(&self) -> Option<Provider> {
        self.0.provider_id.clone().map(Provider)
    }

    fn __repr__(&self) -> String {
        format!("Chart(symbol={:?}, interval={}, range={})", self.0.symbol, match self.0.interval.as_ref() { Some(v) => format!("Some(Interval.{:?})", Interval::from(v)), None => String::from("None") }, match self.0.range.as_ref() { Some(v) => format!("Some(TimeRange.{:?})", TimeRange::from(v)), None => String::from("None") })
    }
}

/// Computed analytics derived from a symbol's dividend history.
#[pyclass(name = "DividendAnalytics")]
pub struct DividendAnalytics(::finance_query::DividendAnalytics);

#[pymethods]
impl DividendAnalytics {
    /// Total dividends paid in the requested range
    #[getter]
    fn total_paid(&self) -> f64 {
        self.0.total_paid.clone()
    }

    #[setter]
    fn set_total_paid(&mut self, value: f64) {
        self.0.total_paid = value;
    }

    /// Number of dividend payments in the requested range
    #[getter]
    fn payment_count(&self) -> usize {
        self.0.payment_count.clone()
    }

    #[setter]
    fn set_payment_count(&mut self, value: usize) {
        self.0.payment_count = value;
    }

    /// Average dividend per payment
    #[getter]
    fn average_payment(&self) -> f64 {
        self.0.average_payment.clone()
    }

    #[setter]
    fn set_average_payment(&mut self, value: f64) {
        self.0.average_payment = value;
    }

    /// Compound Annual Growth Rate of the dividend amount.
    #[getter]
    fn cagr(&self) -> Option<f64> {
        self.0.cagr.clone()
    }

    #[setter]
    fn set_cagr(&mut self, value: Option<f64>) {
        self.0.cagr = value;
    }

    /// Most recent dividend payment
    #[getter]
    fn last_payment(&self) -> Option<Dividend> {
        self.0.last_payment.clone().map(Dividend)
    }

    /// Earliest dividend payment in the requested range
    #[getter]
    fn first_payment(&self) -> Option<Dividend> {
        self.0.first_payment.clone().map(Dividend)
    }

    fn __repr__(&self) -> String {
        format!("DividendAnalytics(total_paid={:?}, payment_count={:?}, average_payment={:?}, cagr={:?})", self.0.total_paid, self.0.payment_count, self.0.average_payment, self.0.cagr)
    }
}

/// Public capital gain data
#[pyclass(name = "CapitalGain")]
pub struct CapitalGain(::finance_query::CapitalGain);

#[pymethods]
impl CapitalGain {
    /// Timestamp (Unix)
    #[getter]
    fn timestamp(&self) -> i64 {
        self.0.timestamp.clone()
    }

    #[setter]
    fn set_timestamp(&mut self, value: i64) {
        self.0.timestamp = value;
    }

    /// Capital gain amount per share
    #[getter]
    fn amount(&self) -> f64 {
        self.0.amount.clone()
    }

    #[setter]
    fn set_amount(&mut self, value: f64) {
        self.0.amount = value;
    }

    /// Which data provider served this data (e.g., "yahoo", "polygon").
    #[getter]
    fn provider_id(&self) -> Option<Provider> {
        self.0.provider_id.clone().map(Provider)
    }

    fn __repr__(&self) -> String {
        format!("CapitalGain(timestamp={:?}, amount={:?})", self.0.timestamp, self.0.amount)
    }
}

/// Public dividend data
#[pyclass(name = "Dividend")]
pub struct Dividend(::finance_query::Dividend);

#[pymethods]
impl Dividend {
    /// Timestamp (Unix)
    #[getter]
    fn timestamp(&self) -> i64 {
        self.0.timestamp.clone()
    }

    #[setter]
    fn set_timestamp(&mut self, value: i64) {
        self.0.timestamp = value;
    }

    /// Dividend amount per share
    #[getter]
    fn amount(&self) -> f64 {
        self.0.amount.clone()
    }

    #[setter]
    fn set_amount(&mut self, value: f64) {
        self.0.amount = value;
    }

    /// Which data provider served this data (e.g., "yahoo", "polygon").
    #[getter]
    fn provider_id(&self) -> Option<Provider> {
        self.0.provider_id.clone().map(Provider)
    }

    fn __repr__(&self) -> String {
        format!("Dividend(timestamp={:?}, amount={:?})", self.0.timestamp, self.0.amount)
    }
}

/// Public stock split data
#[pyclass(name = "Split")]
pub struct Split(::finance_query::Split);

#[pymethods]
impl Split {
    /// Timestamp (Unix)
    #[getter]
    fn timestamp(&self) -> i64 {
        self.0.timestamp.clone()
    }

    #[setter]
    fn set_timestamp(&mut self, value: i64) {
        self.0.timestamp = value;
    }

    /// Numerator of the split ratio
    #[getter]
    fn numerator(&self) -> f64 {
        self.0.numerator.clone()
    }

    #[setter]
    fn set_numerator(&mut self, value: f64) {
        self.0.numerator = value;
    }

    /// Denominator of the split ratio
    #[getter]
    fn denominator(&self) -> f64 {
        self.0.denominator.clone()
    }

    #[setter]
    fn set_denominator(&mut self, value: f64) {
        self.0.denominator = value;
    }

    /// Split ratio as string (e.g., "2:1", "10:1")
    #[getter]
    fn ratio(&self) -> String {
        self.0.ratio.clone()
    }

    #[setter]
    fn set_ratio(&mut self, value: String) {
        self.0.ratio = value;
    }

    /// Which data provider served this data (e.g., "yahoo", "polygon").
    #[getter]
    fn provider_id(&self) -> Option<Provider> {
        self.0.provider_id.clone().map(Provider)
    }

    fn __repr__(&self) -> String {
        format!("Split(timestamp={:?}, numerator={:?}, denominator={:?}, ratio={:?})", self.0.timestamp, self.0.numerator, self.0.denominator, self.0.ratio)
    }
}

/// Metadata for chart data
#[pyclass(name = "ChartMeta")]
pub struct ChartMeta(::finance_query::ChartMeta);

#[pymethods]
impl ChartMeta {
    /// Stock symbol
    #[getter]
    fn symbol(&self) -> String {
        self.0.symbol.clone()
    }

    #[setter]
    fn set_symbol(&mut self, value: String) {
        self.0.symbol = value;
    }

    /// Currency
    #[getter]
    fn currency(&self) -> Option<String> {
        self.0.currency.clone()
    }

    #[setter]
    fn set_currency(&mut self, value: Option<String>) {
        self.0.currency = value;
    }

    /// Exchange name
    #[getter]
    fn exchange_name(&self) -> Option<String> {
        self.0.exchange_name.clone()
    }

    #[setter]
    fn set_exchange_name(&mut self, value: Option<String>) {
        self.0.exchange_name = value;
    }

    /// Full exchange name
    #[getter]
    fn full_exchange_name(&self) -> Option<String> {
        self.0.full_exchange_name.clone()
    }

    #[setter]
    fn set_full_exchange_name(&mut self, value: Option<String>) {
        self.0.full_exchange_name = value;
    }

    /// Instrument type
    #[getter]
    fn instrument_type(&self) -> Option<String> {
        self.0.instrument_type.clone()
    }

    #[setter]
    fn set_instrument_type(&mut self, value: Option<String>) {
        self.0.instrument_type = value;
    }

    /// First trade date (Unix timestamp)
    #[getter]
    fn first_trade_date(&self) -> Option<i64> {
        self.0.first_trade_date.clone()
    }

    #[setter]
    fn set_first_trade_date(&mut self, value: Option<i64>) {
        self.0.first_trade_date = value;
    }

    /// Regular market time (Unix timestamp)
    #[getter]
    fn regular_market_time(&self) -> Option<i64> {
        self.0.regular_market_time.clone()
    }

    #[setter]
    fn set_regular_market_time(&mut self, value: Option<i64>) {
        self.0.regular_market_time = value;
    }

    /// Has pre/post market data
    #[getter]
    fn has_pre_post_market_data(&self) -> Option<bool> {
        self.0.has_pre_post_market_data.clone()
    }

    #[setter]
    fn set_has_pre_post_market_data(&mut self, value: Option<bool>) {
        self.0.has_pre_post_market_data = value;
    }

    /// GMT offset
    #[getter]
    fn gmt_offset(&self) -> Option<i64> {
        self.0.gmt_offset.clone()
    }

    #[setter]
    fn set_gmt_offset(&mut self, value: Option<i64>) {
        self.0.gmt_offset = value;
    }

    /// Timezone
    #[getter]
    fn timezone(&self) -> Option<String> {
        self.0.timezone.clone()
    }

    #[setter]
    fn set_timezone(&mut self, value: Option<String>) {
        self.0.timezone = value;
    }

    /// Exchange timezone name
    #[getter]
    fn exchange_timezone_name(&self) -> Option<String> {
        self.0.exchange_timezone_name.clone()
    }

    #[setter]
    fn set_exchange_timezone_name(&mut self, value: Option<String>) {
        self.0.exchange_timezone_name = value;
    }

    /// Regular market price
    #[getter]
    fn regular_market_price(&self) -> Option<f64> {
        self.0.regular_market_price.clone()
    }

    #[setter]
    fn set_regular_market_price(&mut self, value: Option<f64>) {
        self.0.regular_market_price = value;
    }

    /// Fifty two week high
    #[getter]
    fn fifty_two_week_high(&self) -> Option<f64> {
        self.0.fifty_two_week_high.clone()
    }

    #[setter]
    fn set_fifty_two_week_high(&mut self, value: Option<f64>) {
        self.0.fifty_two_week_high = value;
    }

    /// Fifty two week low
    #[getter]
    fn fifty_two_week_low(&self) -> Option<f64> {
        self.0.fifty_two_week_low.clone()
    }

    #[setter]
    fn set_fifty_two_week_low(&mut self, value: Option<f64>) {
        self.0.fifty_two_week_low = value;
    }

    /// Regular market day high
    #[getter]
    fn regular_market_day_high(&self) -> Option<f64> {
        self.0.regular_market_day_high.clone()
    }

    #[setter]
    fn set_regular_market_day_high(&mut self, value: Option<f64>) {
        self.0.regular_market_day_high = value;
    }

    /// Regular market day low
    #[getter]
    fn regular_market_day_low(&self) -> Option<f64> {
        self.0.regular_market_day_low.clone()
    }

    #[setter]
    fn set_regular_market_day_low(&mut self, value: Option<f64>) {
        self.0.regular_market_day_low = value;
    }

    /// Regular market volume
    #[getter]
    fn regular_market_volume(&self) -> Option<i64> {
        self.0.regular_market_volume.clone()
    }

    #[setter]
    fn set_regular_market_volume(&mut self, value: Option<i64>) {
        self.0.regular_market_volume = value;
    }

    /// Chart previous close
    #[getter]
    fn chart_previous_close(&self) -> Option<f64> {
        self.0.chart_previous_close.clone()
    }

    #[setter]
    fn set_chart_previous_close(&mut self, value: Option<f64>) {
        self.0.chart_previous_close = value;
    }

    /// Previous close
    #[getter]
    fn previous_close(&self) -> Option<f64> {
        self.0.previous_close.clone()
    }

    #[setter]
    fn set_previous_close(&mut self, value: Option<f64>) {
        self.0.previous_close = value;
    }

    /// Price hint (decimal places)
    #[getter]
    fn price_hint(&self) -> Option<i32> {
        self.0.price_hint.clone()
    }

    #[setter]
    fn set_price_hint(&mut self, value: Option<i32>) {
        self.0.price_hint = value;
    }

    /// Data granularity
    #[getter]
    fn data_granularity(&self) -> Option<String> {
        self.0.data_granularity.clone()
    }

    #[setter]
    fn set_data_granularity(&mut self, value: Option<String>) {
        self.0.data_granularity = value;
    }

    /// Range
    #[getter]
    fn range(&self) -> Option<String> {
        self.0.range.clone()
    }

    #[setter]
    fn set_range(&mut self, value: Option<String>) {
        self.0.range = value;
    }

    /// Which data provider served this data (e.g., "yahoo", "polygon").
    #[getter]
    fn provider_id(&self) -> Option<Provider> {
        self.0.provider_id.clone().map(Provider)
    }

    fn __repr__(&self) -> String {
        format!("ChartMeta(symbol={:?}, currency={:?}, exchange_name={:?}, full_exchange_name={:?}, instrument_type={:?}, first_trade_date={:?}, regular_market_time={:?}, has_pre_post_market_data={:?}, gmt_offset={:?}, timezone={:?}, exchange_timezone_name={:?}, regular_market_price={:?}, fifty_two_week_high={:?}, fifty_two_week_low={:?}, regular_market_day_high={:?}, regular_market_day_low={:?}, regular_market_volume={:?}, chart_previous_close={:?}, previous_close={:?}, price_hint={:?}, data_granularity={:?}, range={:?})", self.0.symbol, self.0.currency, self.0.exchange_name, self.0.full_exchange_name, self.0.instrument_type, self.0.first_trade_date, self.0.regular_market_time, self.0.has_pre_post_market_data, self.0.gmt_offset, self.0.timezone, self.0.exchange_timezone_name, self.0.regular_market_price, self.0.fifty_two_week_high, self.0.fifty_two_week_low, self.0.regular_market_day_high, self.0.regular_market_day_low, self.0.regular_market_volume, self.0.chart_previous_close, self.0.previous_close, self.0.price_hint, self.0.data_granularity, self.0.range)
    }
}

/// One earnings call transcript.
#[pyclass(name = "EarningsTranscript")]
pub struct EarningsTranscript(::finance_query::EarningsTranscript);

#[pymethods]
impl EarningsTranscript {
    /// Ticker symbol.
    #[getter]
    fn symbol(&self) -> Option<String> {
        self.0.symbol.clone()
    }

    #[setter]
    fn set_symbol(&mut self, value: Option<String>) {
        self.0.symbol = value;
    }

    /// Fiscal quarter (e.g. `"Q4"`).
    #[getter]
    fn quarter(&self) -> Option<String> {
        self.0.quarter.clone()
    }

    #[setter]
    fn set_quarter(&mut self, value: Option<String>) {
        self.0.quarter = value;
    }

    /// Fiscal year.
    #[getter]
    fn year(&self) -> Option<i32> {
        self.0.year.clone()
    }

    #[setter]
    fn set_year(&mut self, value: Option<i32>) {
        self.0.year = value;
    }

    /// Call date (`YYYY-MM-DD`), when the provider reports one.
    #[getter]
    fn date(&self) -> Option<String> {
        self.0.date.clone()
    }

    #[setter]
    fn set_date(&mut self, value: Option<String>) {
        self.0.date = value;
    }

    /// Full transcript text.
    #[getter]
    fn text(&self) -> String {
        self.0.text.clone()
    }

    #[setter]
    fn set_text(&mut self, value: String) {
        self.0.text = value;
    }

    fn __repr__(&self) -> String {
        format!("EarningsTranscript(symbol={:?}, quarter={:?}, year={:?}, date={:?}, text={:?})", self.0.symbol, self.0.quarter, self.0.year, self.0.date, self.0.text)
    }
}

/// Employee headcount as reported on one filing.
#[pyclass(name = "EmployeeCount")]
pub struct EmployeeCount(::finance_query::EmployeeCount);

#[pymethods]
impl EmployeeCount {
    /// Ticker symbol.
    #[getter]
    fn symbol(&self) -> Option<String> {
        self.0.symbol.clone()
    }

    #[setter]
    fn set_symbol(&mut self, value: Option<String>) {
        self.0.symbol = value;
    }

    /// SEC Central Index Key of the filer.
    #[getter]
    fn cik(&self) -> Option<String> {
        self.0.cik.clone()
    }

    #[setter]
    fn set_cik(&mut self, value: Option<String>) {
        self.0.cik = value;
    }

    /// Company name as filed.
    #[getter]
    fn company_name(&self) -> Option<String> {
        self.0.company_name.clone()
    }

    #[setter]
    fn set_company_name(&mut self, value: Option<String>) {
        self.0.company_name = value;
    }

    /// Number of employees reported.
    #[getter]
    fn employee_count(&self) -> Option<i64> {
        self.0.employee_count.clone()
    }

    #[setter]
    fn set_employee_count(&mut self, value: Option<i64>) {
        self.0.employee_count = value;
    }

    /// Period the count is as of (`YYYY-MM-DD`).
    #[getter]
    fn period_of_report(&self) -> Option<String> {
        self.0.period_of_report.clone()
    }

    #[setter]
    fn set_period_of_report(&mut self, value: Option<String>) {
        self.0.period_of_report = value;
    }

    /// Form the count was reported on (e.g. `"10-K"`).
    #[getter]
    fn form_type(&self) -> Option<String> {
        self.0.form_type.clone()
    }

    #[setter]
    fn set_form_type(&mut self, value: Option<String>) {
        self.0.form_type = value;
    }

    /// Filing date (`YYYY-MM-DD`).
    #[getter]
    fn filing_date(&self) -> Option<String> {
        self.0.filing_date.clone()
    }

    #[setter]
    fn set_filing_date(&mut self, value: Option<String>) {
        self.0.filing_date = value;
    }

    /// URL of the source filing.
    #[getter]
    fn source(&self) -> Option<String> {
        self.0.source.clone()
    }

    #[setter]
    fn set_source(&mut self, value: Option<String>) {
        self.0.source = value;
    }

    fn __repr__(&self) -> String {
        format!("EmployeeCount(symbol={:?}, cik={:?}, company_name={:?}, employee_count={:?}, period_of_report={:?}, form_type={:?}, filing_date={:?}, source={:?})", self.0.symbol, self.0.cik, self.0.company_name, self.0.employee_count, self.0.period_of_report, self.0.form_type, self.0.filing_date, self.0.source)
    }
}

/// One executive's reported compensation for one fiscal year.
#[pyclass(name = "ExecutiveCompensation")]
pub struct ExecutiveCompensation(::finance_query::ExecutiveCompensation);

#[pymethods]
impl ExecutiveCompensation {
    /// Ticker symbol.
    #[getter]
    fn symbol(&self) -> Option<String> {
        self.0.symbol.clone()
    }

    #[setter]
    fn set_symbol(&mut self, value: Option<String>) {
        self.0.symbol = value;
    }

    /// SEC Central Index Key of the filer.
    #[getter]
    fn cik(&self) -> Option<String> {
        self.0.cik.clone()
    }

    #[setter]
    fn set_cik(&mut self, value: Option<String>) {
        self.0.cik = value;
    }

    /// Company name as filed.
    #[getter]
    fn company_name(&self) -> Option<String> {
        self.0.company_name.clone()
    }

    #[setter]
    fn set_company_name(&mut self, value: Option<String>) {
        self.0.company_name = value;
    }

    /// Executive name and position, as a single filed string.
    #[getter]
    fn name_and_position(&self) -> Option<String> {
        self.0.name_and_position.clone()
    }

    #[setter]
    fn set_name_and_position(&mut self, value: Option<String>) {
        self.0.name_and_position = value;
    }

    /// Fiscal year the compensation covers.
    #[getter]
    fn year(&self) -> Option<i32> {
        self.0.year.clone()
    }

    #[setter]
    fn set_year(&mut self, value: Option<i32>) {
        self.0.year = value;
    }

    /// Base salary.
    #[getter]
    fn salary(&self) -> Option<f64> {
        self.0.salary.clone()
    }

    #[setter]
    fn set_salary(&mut self, value: Option<f64>) {
        self.0.salary = value;
    }

    /// Cash bonus.
    #[getter]
    fn bonus(&self) -> Option<f64> {
        self.0.bonus.clone()
    }

    #[setter]
    fn set_bonus(&mut self, value: Option<f64>) {
        self.0.bonus = value;
    }

    /// Value of stock awards.
    #[getter]
    fn stock_award(&self) -> Option<f64> {
        self.0.stock_award.clone()
    }

    #[setter]
    fn set_stock_award(&mut self, value: Option<f64>) {
        self.0.stock_award = value;
    }

    /// Value of option awards.
    #[getter]
    fn option_award(&self) -> Option<f64> {
        self.0.option_award.clone()
    }

    #[setter]
    fn set_option_award(&mut self, value: Option<f64>) {
        self.0.option_award = value;
    }

    /// Non-equity incentive plan compensation.
    #[getter]
    fn incentive_plan_compensation(&self) -> Option<f64> {
        self.0.incentive_plan_compensation.clone()
    }

    #[setter]
    fn set_incentive_plan_compensation(&mut self, value: Option<f64>) {
        self.0.incentive_plan_compensation = value;
    }

    /// All other compensation.
    #[getter]
    fn other_compensation(&self) -> Option<f64> {
        self.0.other_compensation.clone()
    }

    #[setter]
    fn set_other_compensation(&mut self, value: Option<f64>) {
        self.0.other_compensation = value;
    }

    /// Total compensation.
    #[getter]
    fn total(&self) -> Option<f64> {
        self.0.total.clone()
    }

    #[setter]
    fn set_total(&mut self, value: Option<f64>) {
        self.0.total = value;
    }

    /// Filing date of the source document (`YYYY-MM-DD`).
    #[getter]
    fn filing_date(&self) -> Option<String> {
        self.0.filing_date.clone()
    }

    #[setter]
    fn set_filing_date(&mut self, value: Option<String>) {
        self.0.filing_date = value;
    }

    /// URL of the source filing.
    #[getter]
    fn url(&self) -> Option<String> {
        self.0.url.clone()
    }

    #[setter]
    fn set_url(&mut self, value: Option<String>) {
        self.0.url = value;
    }

    fn __repr__(&self) -> String {
        format!("ExecutiveCompensation(symbol={:?}, cik={:?}, company_name={:?}, name_and_position={:?}, year={:?}, salary={:?}, bonus={:?}, stock_award={:?}, option_award={:?}, incentive_plan_compensation={:?}, other_compensation={:?}, total={:?}, filing_date={:?}, url={:?})", self.0.symbol, self.0.cik, self.0.company_name, self.0.name_and_position, self.0.year, self.0.salary, self.0.bonus, self.0.stock_award, self.0.option_award, self.0.incentive_plan_compensation, self.0.other_compensation, self.0.total, self.0.filing_date, self.0.url)
    }
}

/// A news article
#[pyclass(name = "News")]
pub struct News(::finance_query::News);

#[pymethods]
impl News {
    /// Article title
    #[getter]
    fn title(&self) -> String {
        self.0.title.clone()
    }

    #[setter]
    fn set_title(&mut self, value: String) {
        self.0.title = value;
    }

    /// Article URL
    #[getter]
    fn link(&self) -> String {
        self.0.link.clone()
    }

    #[setter]
    fn set_link(&mut self, value: String) {
        self.0.link = value;
    }

    /// News source/publisher (e.g., "Reuters", "Bloomberg")
    #[getter]
    fn source(&self) -> String {
        self.0.source.clone()
    }

    #[setter]
    fn set_source(&mut self, value: String) {
        self.0.source = value;
    }

    /// Thumbnail image URL
    #[getter]
    fn img(&self) -> String {
        self.0.img.clone()
    }

    #[setter]
    fn set_img(&mut self, value: String) {
        self.0.img = value;
    }

    /// Relative time when the news was published (e.g., "1 hour ago", "2 days ago")
    #[getter]
    fn time(&self) -> String {
        self.0.time.clone()
    }

    #[setter]
    fn set_time(&mut self, value: String) {
        self.0.time = value;
    }

    /// Which provider supplied this article (None = Yahoo Finance default)
    #[getter]
    fn provider_id(&self) -> Option<Provider> {
        self.0.provider_id.clone().map(Provider)
    }

    /// Sentiment score for this article's title (VADER lexicon-based).
    #[getter]
    fn sentiment(&self) -> Option<Sentiment> {
        self.0.sentiment.clone().map(Sentiment)
    }

    fn __repr__(&self) -> String {
        format!("News(title={:?}, link={:?}, source={:?}, img={:?}, time={:?})", self.0.title, self.0.link, self.0.source, self.0.img, self.0.time)
    }
}

/// A company press release.
#[pyclass(name = "PressRelease")]
pub struct PressRelease(::finance_query::PressRelease);

#[pymethods]
impl PressRelease {
    /// Ticker symbol.
    #[getter]
    fn symbol(&self) -> Option<String> {
        self.0.symbol.clone()
    }

    #[setter]
    fn set_symbol(&mut self, value: Option<String>) {
        self.0.symbol = value;
    }

    /// Publication date/time as reported by the provider.
    #[getter]
    fn date(&self) -> Option<String> {
        self.0.date.clone()
    }

    #[setter]
    fn set_date(&mut self, value: Option<String>) {
        self.0.date = value;
    }

    /// Release title.
    #[getter]
    fn title(&self) -> Option<String> {
        self.0.title.clone()
    }

    #[setter]
    fn set_title(&mut self, value: Option<String>) {
        self.0.title = value;
    }

    /// Full release text.
    #[getter]
    fn text(&self) -> Option<String> {
        self.0.text.clone()
    }

    #[setter]
    fn set_text(&mut self, value: Option<String>) {
        self.0.text = value;
    }

    fn __repr__(&self) -> String {
        format!("PressRelease(symbol={:?}, date={:?}, title={:?}, text={:?})", self.0.symbol, self.0.date, self.0.title, self.0.text)
    }
}

/// Fully typed recommendation data
#[pyclass(name = "Recommendation")]
pub struct Recommendation(::finance_query::Recommendation);

#[pymethods]
impl Recommendation {
    /// Symbol that was queried
    #[getter]
    fn symbol(&self) -> String {
        self.0.symbol.clone()
    }

    #[setter]
    fn set_symbol(&mut self, value: String) {
        self.0.symbol = value;
    }

    /// Recommended/similar symbols with scores
    #[getter]
    fn recommendations(&self) -> SimilarSymbolSeq {
        SimilarSymbolSeq::new(self.0.recommendations.clone())
    }

    /// Which provider supplied this data (None = Yahoo Finance default)
    #[getter]
    fn provider_id(&self) -> Option<Provider> {
        self.0.provider_id.clone().map(Provider)
    }

    fn __repr__(&self) -> String {
        format!("Recommendation(symbol={:?})", self.0.symbol)
    }
}

/// A similar/recommended symbol with score
#[pyclass(name = "SimilarSymbol")]
pub struct SimilarSymbol(::finance_query::SimilarSymbol);

#[pymethods]
impl SimilarSymbol {
    /// Stock symbol
    #[getter]
    fn symbol(&self) -> String {
        self.0.symbol.clone()
    }

    #[setter]
    fn set_symbol(&mut self, value: String) {
        self.0.symbol = value;
    }

    /// Recommendation score (higher = more similar)
    #[getter]
    fn score(&self) -> f64 {
        self.0.score.clone()
    }

    #[setter]
    fn set_score(&mut self, value: f64) {
        self.0.score = value;
    }

    fn __repr__(&self) -> String {
        format!("SimilarSymbol(symbol={:?}, score={:?})", self.0.symbol, self.0.score)
    }
}

/// Sentiment score for a news article or transcript segment.
#[pyclass(name = "Sentiment")]
pub struct Sentiment(::finance_query::Sentiment);

#[pymethods]
impl Sentiment {
    /// Directional classification.
    #[getter]
    fn label(&self) -> SentimentLabel {
        (&self.0.label).into()
    }

    #[setter]
    fn set_label(&mut self, value: SentimentLabel) {
        self.0.label = value.into();
    }

    /// Compound score: -1.0 (most bearish) to +1.0 (most bullish).
    #[getter]
    fn score(&self) -> f64 {
        self.0.score.clone()
    }

    #[setter]
    fn set_score(&mut self, value: f64) {
        self.0.score = value;
    }

    /// Confidence: 0.0 to 1.0 (magnitude of the compound score).
    #[getter]
    fn confidence(&self) -> f64 {
        self.0.confidence.clone()
    }

    #[setter]
    fn set_confidence(&mut self, value: f64) {
        self.0.confidence = value;
    }

    fn __repr__(&self) -> String {
        format!("Sentiment(label=SentimentLabel.{:?}, score={:?}, confidence={:?})", SentimentLabel::from(&self.0.label), self.0.score, self.0.confidence)
    }
}

/// Directional sentiment classification for a piece of text.
#[pyclass(name = "SentimentLabel", eq, eq_int, from_py_object)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SentimentLabel {
    Bullish,
    Neutral,
    Bearish,
}

impl ::std::convert::From<::finance_query::SentimentLabel> for SentimentLabel {
    #[allow(unreachable_patterns)]
    fn from(value: ::finance_query::SentimentLabel) -> Self {
        match value {
            ::finance_query::SentimentLabel::Bullish => SentimentLabel::Bullish,
            ::finance_query::SentimentLabel::Neutral => SentimentLabel::Neutral,
            ::finance_query::SentimentLabel::Bearish => SentimentLabel::Bearish,
            _ => ::std::unreachable!("::finance_query::SentimentLabel gained a variant this binding was not generated for"),
        }
    }
}

// A mirrored enum has no derived `Clone`; a field getter converts through
// this one instead of cloning an owned copy just to consume it.
impl ::std::convert::From<&::finance_query::SentimentLabel> for SentimentLabel {
    #[allow(unreachable_patterns)]
    fn from(value: &::finance_query::SentimentLabel) -> Self {
        match value {
            ::finance_query::SentimentLabel::Bullish => SentimentLabel::Bullish,
            ::finance_query::SentimentLabel::Neutral => SentimentLabel::Neutral,
            ::finance_query::SentimentLabel::Bearish => SentimentLabel::Bearish,
            _ => ::std::unreachable!("::finance_query::SentimentLabel gained a variant this binding was not generated for"),
        }
    }
}

impl ::std::convert::From<SentimentLabel> for ::finance_query::SentimentLabel {
    fn from(value: SentimentLabel) -> Self {
        match value {
            SentimentLabel::Bullish => ::finance_query::SentimentLabel::Bullish,
            SentimentLabel::Neutral => ::finance_query::SentimentLabel::Neutral,
            SentimentLabel::Bearish => ::finance_query::SentimentLabel::Bearish,
        }
    }
}

/// Typed identifier for a financial data provider.
#[pyclass(name = "Provider")]
pub struct Provider(::finance_query::Provider);

/// The primary entry point for querying financial data for a single symbol.
#[pyclass(name = "Ticker")]
pub struct Ticker(::finance_query::Ticker);

#[pymethods]
impl Ticker {
    /// Get capital gains distribution history.
    async fn capital_gains(&self, range: TimeRange) -> PyResult<Vec<CapitalGain>> {
        Ok(OnRuntime::new(self.0.capital_gains(range.into())).await.map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(CapitalGain).collect())
    }

    /// Blocking form of `capital_gains`: runs the call to completion on the package's runtime.
    fn capital_gains_blocking(&self, range: TimeRange) -> PyResult<Vec<CapitalGain>> {
        Ok(runtime().block_on(self.0.capital_gains(range.into())).map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(CapitalGain).collect())
    }

    /// Get historical OHLCV chart data.
    async fn chart(&self, interval: Interval, range: TimeRange) -> PyResult<Chart> {
        Ok(Chart(OnRuntime::new(self.0.chart(interval.into(), range.into())).await.map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Blocking form of `chart`: runs the call to completion on the package's runtime.
    fn chart_blocking(&self, interval: Interval, range: TimeRange) -> PyResult<Chart> {
        Ok(Chart(runtime().block_on(self.0.chart(interval.into(), range.into())).map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Get chart data for a custom start/end timestamp range.
    async fn chart_range(&self, interval: Interval, start: i64, end: i64) -> PyResult<Chart> {
        Ok(Chart(OnRuntime::new(self.0.chart_range(interval.into(), start, end)).await.map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Blocking form of `chart_range`: runs the call to completion on the package's runtime.
    fn chart_range_blocking(&self, interval: Interval, start: i64, end: i64) -> PyResult<Chart> {
        Ok(Chart(runtime().block_on(self.0.chart_range(interval.into(), start, end)).map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Compute dividend analytics for the requested time range.
    async fn dividend_analytics(&self, range: TimeRange) -> PyResult<DividendAnalytics> {
        Ok(DividendAnalytics(OnRuntime::new(self.0.dividend_analytics(range.into())).await.map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Blocking form of `dividend_analytics`: runs the call to completion on the package's runtime.
    fn dividend_analytics_blocking(&self, range: TimeRange) -> PyResult<DividendAnalytics> {
        Ok(DividendAnalytics(runtime().block_on(self.0.dividend_analytics(range.into())).map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Get dividend history.
    async fn dividends(&self, range: TimeRange) -> PyResult<Vec<Dividend>> {
        Ok(OnRuntime::new(self.0.dividends(range.into())).await.map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(Dividend).collect())
    }

    /// Blocking form of `dividends`: runs the call to completion on the package's runtime.
    fn dividends_blocking(&self, range: TimeRange) -> PyResult<Vec<Dividend>> {
        Ok(runtime().block_on(self.0.dividends(range.into())).map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(Dividend).collect())
    }

    /// Fetch an earnings call transcript, provider-neutral shape, via the
    async fn earnings_transcript(&self, quarter: Option<String>, year: Option<i32>) -> PyResult<EarningsTranscript> {
        Ok(EarningsTranscript(OnRuntime::new(self.0.earnings_transcript(quarter.as_deref(), year)).await.map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Blocking form of `earnings_transcript`: runs the call to completion on the package's runtime.
    fn earnings_transcript_blocking(&self, quarter: Option<String>, year: Option<i32>) -> PyResult<EarningsTranscript> {
        Ok(EarningsTranscript(runtime().block_on(self.0.earnings_transcript(quarter.as_deref(), year)).map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Fetch reported employee headcount history (most recent period first) via
    async fn employee_count(&self) -> PyResult<Vec<EmployeeCount>> {
        Ok(OnRuntime::new(self.0.employee_count()).await.map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(EmployeeCount).collect())
    }

    /// Blocking form of `employee_count`: runs the call to completion on the package's runtime.
    fn employee_count_blocking(&self) -> PyResult<Vec<EmployeeCount>> {
        Ok(runtime().block_on(self.0.employee_count()).map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(EmployeeCount).collect())
    }

    /// Fetch reported executive compensation (most recent fiscal year first)
    async fn executive_compensation(&self) -> PyResult<Vec<ExecutiveCompensation>> {
        Ok(OnRuntime::new(self.0.executive_compensation()).await.map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(ExecutiveCompensation).collect())
    }

    /// Blocking form of `executive_compensation`: runs the call to completion on the package's runtime.
    fn executive_compensation_blocking(&self) -> PyResult<Vec<ExecutiveCompensation>> {
        Ok(runtime().block_on(self.0.executive_compensation()).map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(ExecutiveCompensation).collect())
    }

    /// Get news articles for this symbol.
    async fn news(&self) -> PyResult<Vec<News>> {
        Ok(OnRuntime::new(self.0.news()).await.map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(News).collect())
    }

    /// Blocking form of `news`: runs the call to completion on the package's runtime.
    fn news_blocking(&self) -> PyResult<Vec<News>> {
        Ok(runtime().block_on(self.0.news()).map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(News).collect())
    }

    /// Average sentiment across recent news headlines for this symbol.
    async fn news_sentiment(&self) -> PyResult<Sentiment> {
        Ok(Sentiment(OnRuntime::new(self.0.news_sentiment()).await.map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Blocking form of `news_sentiment`: runs the call to completion on the package's runtime.
    fn news_sentiment_blocking(&self) -> PyResult<Sentiment> {
        Ok(Sentiment(runtime().block_on(self.0.news_sentiment()).map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Fetch the company's own press releases via the configured
    async fn press_releases(&self, limit: u32) -> PyResult<Vec<PressRelease>> {
        Ok(OnRuntime::new(self.0.press_releases(limit)).await.map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(PressRelease).collect())
    }

    /// Blocking form of `press_releases`: runs the call to completion on the package's runtime.
    fn press_releases_blocking(&self, limit: u32) -> PyResult<Vec<PressRelease>> {
        Ok(runtime().block_on(self.0.press_releases(limit)).map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(PressRelease).collect())
    }

    /// Get analyst recommendations and similar symbols.
    async fn recommendations(&self, limit: u32) -> PyResult<Recommendation> {
        Ok(Recommendation(OnRuntime::new(self.0.recommendations(limit)).await.map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Blocking form of `recommendations`: runs the call to completion on the package's runtime.
    fn recommendations_blocking(&self, limit: u32) -> PyResult<Recommendation> {
        Ok(Recommendation(runtime().block_on(self.0.recommendations(limit)).map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Get stock split history.
    async fn splits(&self, range: TimeRange) -> PyResult<Vec<Split>> {
        Ok(OnRuntime::new(self.0.splits(range.into())).await.map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(Split).collect())
    }

    /// Blocking form of `splits`: runs the call to completion on the package's runtime.
    fn splits_blocking(&self, range: TimeRange) -> PyResult<Vec<Split>> {
        Ok(runtime().block_on(self.0.splits(range.into())).map_err(BindErrorfinancequeryerrorFinanceError)?.into_iter().map(Split).collect())
    }

    /// Returns the ticker symbol.
    fn symbol(&self) -> String {
        self.0.symbol().to_owned()
    }

    /// Creates a new ticker with default configuration.
    #[staticmethod]
    async fn new(symbol: String) -> PyResult<Ticker> {
        Ok(Ticker(OnRuntime::new(::finance_query::Ticker::new(symbol)).await.map_err(BindErrorfinancequeryerrorFinanceError)?))
    }

    /// Blocking form of `new`: runs the call to completion on the package's runtime.
    #[staticmethod]
    fn new_blocking(symbol: String) -> PyResult<Ticker> {
        Ok(Ticker(runtime().block_on(::finance_query::Ticker::new(symbol)).map_err(BindErrorfinancequeryerrorFinanceError)?))
    }
}

#[pymodule(gil_used = false)]
fn finance_query(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<F64Array>()?;
    m.add_class::<I64Array>()?;
    m.add_class::<CandleSeq>()?;
    m.add_class::<SimilarSymbolSeq>()?;
    m.add_class::<Interval>()?;
    m.add_class::<TimeRange>()?;
    m.add_class::<Candle>()?;
    m.add_class::<Chart>()?;
    m.add_class::<DividendAnalytics>()?;
    m.add_class::<CapitalGain>()?;
    m.add_class::<Dividend>()?;
    m.add_class::<Split>()?;
    m.add_class::<ChartMeta>()?;
    m.add_class::<EarningsTranscript>()?;
    m.add_class::<EmployeeCount>()?;
    m.add_class::<ExecutiveCompensation>()?;
    m.add_class::<News>()?;
    m.add_class::<PressRelease>()?;
    m.add_class::<Recommendation>()?;
    m.add_class::<SimilarSymbol>()?;
    m.add_class::<Sentiment>()?;
    m.add_class::<SentimentLabel>()?;
    m.add_class::<Provider>()?;
    m.add_class::<Ticker>()?;
    m.add("Error", m.py().get_type::<Error>())?;
    m.add("BacktestError", m.py().get_type::<BacktestError>())?;
    m.add("InvalidParameter", m.py().get_type::<InvalidParameter>())?;
    m.add("InsufficientData", m.py().get_type::<InsufficientData>())?;
    m.add("StrategyError", m.py().get_type::<StrategyError>())?;
    m.add("IndicatorError", m.py().get_type::<IndicatorError>())?;
    m.add("ChartError", m.py().get_type::<ChartError>())?;
    m.add("PositionError", m.py().get_type::<PositionError>())?;
    m.add("FinanceError", m.py().get_type::<FinanceError>())?;
    m.add("AuthenticationFailed", m.py().get_type::<AuthenticationFailed>())?;
    m.add("ProviderNotConfigured", m.py().get_type::<ProviderNotConfigured>())?;
    m.add("SymbolNotFound", m.py().get_type::<SymbolNotFound>())?;
    m.add("RateLimited", m.py().get_type::<RateLimited>())?;
    m.add("HttpError", m.py().get_type::<HttpError>())?;
    m.add("NetworkError", m.py().get_type::<NetworkError>())?;
    m.add("JsonParseError", m.py().get_type::<JsonParseError>())?;
    m.add("ResponseStructureError", m.py().get_type::<ResponseStructureError>())?;
    m.add("InvalidParameterError", m.py().get_type::<InvalidParameterError>())?;
    m.add("Timeout", m.py().get_type::<Timeout>())?;
    m.add("ServerError", m.py().get_type::<ServerError>())?;
    m.add("UnexpectedResponse", m.py().get_type::<UnexpectedResponse>())?;
    m.add("InternalError", m.py().get_type::<InternalError>())?;
    m.add("ApiError", m.py().get_type::<ApiError>())?;
    m.add("RuntimeError", m.py().get_type::<RuntimeError>())?;
    m.add("IndicatorErrorError", m.py().get_type::<IndicatorErrorError>())?;
    m.add("ExternalApiError", m.py().get_type::<ExternalApiError>())?;
    m.add("MacroDataError", m.py().get_type::<MacroDataError>())?;
    m.add("FeedParseError", m.py().get_type::<FeedParseError>())?;
    m.add("NotSupported", m.py().get_type::<NotSupported>())?;
    m.add("NoProviderAvailable", m.py().get_type::<NoProviderAvailable>())?;
    m.add("ProviderNotRegistered", m.py().get_type::<ProviderNotRegistered>())?;
    m.add("TranslationError", m.py().get_type::<TranslationError>())?;
    Ok(())
}
