// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/configuration.md line 188
fn main() {
    use finance_query::Interval;

    // Intraday trading
    let _ = Interval::OneMinute; // 1m candles
    let _ = Interval::FiveMinutes; // 5m candles
    let _ = Interval::FifteenMinutes; // 15m candles
    let _ = Interval::ThirtyMinutes; // 30m candles
    let _ = Interval::OneHour; // 1h candles

    // Daily and longer
    let _ = Interval::OneDay; // Daily candles (most common)
    let _ = Interval::OneWeek; // Weekly candles
    let _ = Interval::OneMonth; // Monthly candles
    let _ = Interval::ThreeMonths; // Quarterly candles

    println!("OneMinute.as_str() = {:?}", Interval::OneMinute.as_str());
    println!("OneDay.as_str()    = {:?}", Interval::OneDay.as_str());
}
