// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 1662
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::Ticker;

    let ticker = Ticker::new("AAPL").await?;

    // First access to ANY quote module -> 1 API call fetching ALL ~30 modules
    let price = ticker.price().await?;

    // All subsequent module accesses -> 0 API calls (same Ticker instance)
    let financial_data = ticker.financial_data().await?; // no network
    let profile = ticker.asset_profile().await?; // no network
    let stats = ticker.key_stats().await?; // no network

    println!(
        "price={} financial_data={} asset_profile={} key_stats={}",
        price.is_some(),
        financial_data.is_some(),
        profile.is_some(),
        stats.is_some(),
    );
    Ok(())
}
