// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/configuration.md line 220
fn main() {
    use finance_query::TimeRange;

    // Short term
    let _ = TimeRange::OneDay; // 1 day
    let _ = TimeRange::FiveDays; // 5 days
    let _ = TimeRange::OneMonth; // 1 month
    let _ = TimeRange::ThreeMonths; // 3 months
    let _ = TimeRange::SixMonths; // 6 months

    // Long term
    let _ = TimeRange::OneYear; // 1 year
    let _ = TimeRange::TwoYears; // 2 years
    let _ = TimeRange::FiveYears; // 5 years
    let _ = TimeRange::TenYears; // 10 years
    let _ = TimeRange::YearToDate; // From Jan 1 of current year
    let _ = TimeRange::Max; // All available history

    println!("OneMonth.as_str() = {:?}", TimeRange::OneMonth.as_str());
    println!("Max.as_str()      = {:?}", TimeRange::Max.as_str());
}
