// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/finance.md line 224
use finance_query::{Region, finance};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // US market hours (default)
    let hours = finance::hours(None).await?;

    // Japan market hours
    let hours = finance::hours(Some(Region::Japan)).await?;

    for market in &hours.markets {
        println!("{}: {}", market.name, market.status);
        println!("  Open: {:?}", market.open);
        println!("  Close: {:?}", market.close);
    }
    Ok(())
}
