// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/dataframe.md line 240
#[cfg(feature = "dataframe")]
mod soothfast_capture_body {
    use finance_query::{Interval, Ticker, TimeRange};

    #[tokio::main]
    pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let ticker = Ticker::new("TSLA").await?;
        let indicators = ticker
            .indicators(Interval::OneDay, TimeRange::ThreeMonths)
            .await?;

        // Convert to single-row DataFrame with all 52 indicators
        let df = indicators.to_dataframe()?;

        // Access specific scalar indicators. Nested indicators (e.g. `macd`,
        // an Option<MacdData>) are skipped by the derive — read them off the struct.
        println!("RSI(14): {:?}", df.column("rsi_14")?);
        println!("ADX(14): {:?}", df.column("adx_14")?);
        Ok(())
    }
}
#[cfg(feature = "dataframe")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "dataframe"))]
fn main() {}
