// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/error-handling.md line 108
fn main() {
    use finance_query::{ErrorCategory, FinanceError};

    let error = FinanceError::RateLimited { retry_after: None };

    let log_line = match error.category() {
        ErrorCategory::Auth => "warn: auth failure",
        ErrorCategory::RateLimit => "warn: rate limited, backing off",
        ErrorCategory::Timeout => "warn: timeout",
        ErrorCategory::Server => "error: upstream server error",
        ErrorCategory::NotFound => "info: symbol not found",
        ErrorCategory::Validation => "warn: invalid input",
        ErrorCategory::Parsing => "error: parse failure",
        ErrorCategory::Other => "error: unclassified failure",
    };
    assert_eq!(log_line, "warn: rate limited, backing off");
    println!("category = {:?}", error.category());
    println!("log_line = {log_line:?}");
}
