// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/tickers.md line 76
use finance_query::Tickers;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Conservative: 3 concurrent requests (large lists or strict rate limits)
    let tickers = Tickers::builder(vec!["AAPL", "MSFT", "GOOGL", "TSLA"])
        .max_concurrency(3)
        .build()
        .await?;
    println!("{} tickers", tickers.len());
    Ok(())
}
