// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/tickers.md line 32
use finance_query::{Region, Tickers};
use std::time::Duration;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let _tickers = Tickers::builder(vec!["AAPL", "MSFT"])
        .region(Region::UnitedStates)
        .timeout(Duration::from_secs(30))
        .build()
        .await?;
    Ok(())
}
