// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 1796
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::Ticker;

    let ticker = Ticker::new("AAPL").await?;
    let news = ticker.news().await?;
    let news_again = ticker.news().await?; // cached

    let recs = ticker.recommendations(10).await?;
    let recs_again = ticker.recommendations(10).await?; // cached

    println!("news articles: {}", news.len());
    println!("news == news_again: {}", news.len() == news_again.len());
    println!("recommendations: {}", recs.recommendations.len());
    println!(
        "recs == recs_again: {}",
        recs.recommendations.len() == recs_again.recommendations.len()
    );
    Ok(())
}
