// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/index.md line 209
fn main() {
    use finance_query::{Capability, Provider};

    println!("| Provider | Capabilities |");
    println!("|----------|--------------|");
    for provider in Provider::all() {
        let declared: Vec<&str> = Capability::all()
            .filter(|c| provider.capabilities().contains(*c))
            .map(Capability::name)
            .collect();
        let declared = match declared.is_empty() {
            true => "none".to_string(),
            false => declared.join(", "),
        };
        println!("| `{}` | {declared} |", provider.as_str());
    }
}
