// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 1605
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::Ticker;
    use std::time::Duration;

    // Default: cached for the lifetime of the handle
    let ticker = Ticker::new("AAPL").await?;

    // Bounded: entries expire after 5 minutes
    let ticker = Ticker::builder("AAPL")
        .cache(Duration::from_secs(300))
        .build()
        .await?;

    // Off: every accessor issues a fresh request
    let ticker = Ticker::builder("AAPL").no_cache().build().await?;
    Ok(())
}
