// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/dataframe.md line 837
#[cfg(feature = "dataframe")]
mod soothfast_capture_body {
    use finance_query::{Interval, Ticker, TimeRange};

    #[tokio::main]
    pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let ticker = Ticker::new("AAPL").await?;
        let chart = ticker.chart(Interval::OneDay, TimeRange::OneMonth).await?;

        match chart.to_dataframe() {
            Ok(df) => {
                println!("DataFrame created: {} rows", df.height());
            }
            Err(e) => {
                eprintln!("DataFrame conversion error: {}", e);
            }
        }
        Ok(())
    }
}
#[cfg(feature = "dataframe")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "dataframe"))]
fn main() {}
