// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 1393
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::{Ticker, finance};

    let ticker = Ticker::new("AAPL").await?;

    // Get latest transcript
    let transcript = finance::earnings_transcript(ticker.symbol(), None, None).await?;

    println!(
        "Transcript for {} - Q{} {}",
        ticker.symbol(),
        transcript.quarter(),
        transcript.year()
    );

    // Access paragraphs with speaker names resolved
    for (paragraph, speaker) in transcript.paragraphs_with_speakers() {
        if let Some(name) = speaker {
            println!("[{:.1}s] {}: {}", paragraph.start, name, paragraph.text);
        }
    }

    // Get a specific quarter transcript
    let _q1 = finance::earnings_transcript(ticker.symbol(), Some("Q1"), Some(2024)).await?;

    // Get all available transcripts (metadata only)
    let all_transcripts = finance::earnings_transcripts(ticker.symbol(), None).await?;

    for meta in &all_transcripts {
        println!(
            "{} {} - {}",
            meta.year.unwrap_or(0),
            meta.quarter.as_deref().unwrap_or("?"),
            meta.title
        );
    }
    Ok(())
}
