// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/finance.md line 328
use finance_query::{Screener, finance};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Top gainers
    let gainers = finance::screener(Screener::DayGainers, 25).await?;

    // Most actives
    let actives = finance::screener(Screener::MostActives, 25).await?;
    println!("Fetched {} most actives", actives.quotes.len());

    // Day losers
    let losers = finance::screener(Screener::DayLosers, 25).await?;
    println!("Fetched {} day losers", losers.quotes.len());

    // Process results
    for quote in &gainers.quotes {
        let change_pct = quote.regular_market_change_percent.raw.unwrap_or(0.0);
        println!("{}: {:+.2}%", quote.symbol, change_pct);
    }
    Ok(())
}
