// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/dataframe.md line 793
#[cfg(feature = "dataframe")]
fn main() {
    use finance_query::Dividend;

    let dividends: Vec<Dividend> = serde_json::from_str(
        r#"[{"timestamp": 1704067200, "amount": 0.24},
            {"timestamp": 1711929600, "amount": 0.25}]"#,
    )
    .unwrap();

    let df = Dividend::vec_to_dataframe(&dividends).unwrap();
    assert_eq!(df.height(), 2);
    assert!(df.column("timestamp").is_ok());
    assert!(df.column("amount").is_ok());
    println!("rows = {}", df.height());
    println!("columns = {:?}", df.get_column_names());
}

#[cfg(not(feature = "dataframe"))]
fn main() {}
