// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/finance.md line 190
use finance_query::{Region, finance};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let _trending = finance::trending(None).await?;
    // Or specify region
    let trending = finance::trending(Some(Region::Singapore)).await?;

    for quote in &trending {
        println!("{}", quote.symbol);
    }
    Ok(())
}
