// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/finance.md line 264
use finance_query::{IndicesRegion, finance};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // All world indices
    let all = finance::indices(None).await?;
    println!("Fetched {} indices", all.success_count());

    // Only Americas indices (^DJI, ^GSPC, ^IXIC, etc.)
    let americas = finance::indices(Some(IndicesRegion::Americas)).await?;
    for (symbol, quote) in &americas.quotes {
        if let (Some(price_fv), Some(change_pct_fv)) = (
            &quote.regular_market_price,
            &quote.regular_market_change_percent,
        ) && let (Some(price), Some(change_pct)) = (price_fv.raw, change_pct_fv.raw)
        {
            println!("{}: {:.2} ({:+.2}%)", symbol, price, change_pct);
        }
    }

    // Other regions
    let europe = finance::indices(Some(IndicesRegion::Europe)).await?;
    let asia = finance::indices(Some(IndicesRegion::AsiaPacific)).await?;
    println!(
        "Fetched {} Europe, {} Asia-Pacific indices",
        europe.success_count(),
        asia.success_count()
    );
    Ok(())
}
