// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/tickers.md line 617
use finance_query::Tickers;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let tickers = Tickers::new(vec!["AAPL", "MSFT"]).await?;

    // Fetch options for all symbols (nearest expiration)
    let response = tickers.options(None).await?;

    // Process options
    for (symbol, options) in &response.options {
        let exp_dates = options.expiration_dates();
        println!("{}: {} expirations", symbol, exp_dates.len());

        // Show calls and puts count for nearest expiration
        let calls = options.calls();
        let puts = options.puts();
        println!("  Calls: {} contracts", calls.len());
        println!("  Puts: {} contracts", puts.len());
    }

    // Fetch for specific expiration date (Unix timestamp)
    let specific_date = 1735689600; // 2025-01-01
    let _response = tickers.options(Some(specific_date)).await?;
    Ok(())
}
