// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/screeners.md line 167
fn main() {
    use finance_query::{EquityField, EquityScreenerQuery, ScreenerFieldExt};

    // US OR Canadian equities, large-cap
    let query = EquityScreenerQuery::new()
        .add_or_conditions(vec![
            EquityField::Region.eq_str("us"),
            EquityField::Region.eq_str("ca"),
        ])
        .add_condition(EquityField::IntradayMarketCap.gt(5_000_000_000.0));

    // Top level is AND: one OR sub-group plus one plain condition
    assert_eq!(query.query.operands.len(), 2);
    println!("top-level operands = {}", query.query.operands.len());
}
