// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/dataframe.md line 100
#[cfg(feature = "dataframe")]
mod soothfast_capture_body {
    use finance_query::{Ticker, format::Both};

    #[tokio::main]
    pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let ticker = Ticker::new("NVDA").await?;
        let quote = ticker.quote::<Both>().await?;

        // Convert to single-row DataFrame
        let df = quote.to_dataframe()?;
        println!("{}", df);
        Ok(())
    }
}
#[cfg(feature = "dataframe")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "dataframe"))]
fn main() {}
