// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/edgar.md line 15
use finance_query::edgar;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Required: Contact email for SEC compliance
    edgar::init("user@example.com")?;
    Ok(())
}
