// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/finance.md line 83
use finance_query::{LookupOptions, LookupType, finance};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Simple lookup
    let _results = finance::lookup("NVDA", &LookupOptions::default()).await?;

    // Lookup equities with logos
    let options = LookupOptions::new()
        .lookup_type(LookupType::Equity)
        .count(10)
        .include_logo(true);

    let results = finance::lookup("tech", &options).await?;
    for quote in &results.quotes {
        let name = quote.short_name.as_deref().unwrap_or("N/A");
        println!("{}: {} - {:?}", quote.symbol, name, quote.logo_url);
    }
    Ok(())
}
