// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/risk.md line 107
#[cfg(feature = "risk")]
fn main() {
    use finance_query::risk::{
        beta, calmar_ratio, historical_var, max_drawdown, parametric_var, sharpe_ratio,
        sortino_ratio,
    };

    // Close-to-close simple returns; real code would derive these from chart data.
    let returns: Vec<f64> = (0..252).map(|i| ((i % 7) as f64 - 3.0) / 100.0).collect();
    let benchmark_returns: Vec<f64> = (0..252).map(|i| ((i % 5) as f64 - 2.0) / 100.0).collect();

    // Value at Risk (positive loss fractions)
    let var_95 = historical_var(&returns, 0.95).unwrap();
    let var_99 = historical_var(&returns, 0.99).unwrap();
    let pvar = parametric_var(&returns, 0.95).unwrap();
    assert!(var_95 > 0.0 && var_99 >= var_95);

    // Risk-adjusted returns (annualised, rf=0, 252 trading days). `None` only
    // for a degenerate all-zero-variance series, so it's safe to unwrap here.
    let sharpe = sharpe_ratio(&returns, 0.0, 252.0).unwrap();
    let sortino = sortino_ratio(&returns, 0.0, 252.0).unwrap();

    // Max drawdown & Calmar
    let dd = max_drawdown(&returns);
    // dd.max_drawdown: f64 (positive fraction)
    // dd.recovery_periods: Option<u64>
    let annualised_return = 0.25; // your computed value
    let years = returns.len() as f64 / 252.0;
    let calmar = calmar_ratio(annualised_return, years, dd.max_drawdown).unwrap();

    // Beta
    let b = beta(&returns, &benchmark_returns).unwrap();

    println!("VaR 95%/99%: {var_95:.4} / {var_99:.4}   parametric VaR 95%: {pvar:.4}");
    println!("Sharpe: {sharpe:.4}   Sortino: {sortino:.4}   Calmar: {calmar:.4}");
    println!("Max drawdown: {:.4}   Beta: {b:.4}", dd.max_drawdown);
}

#[cfg(not(feature = "risk"))]
fn main() {}
