// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 550
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::{Ticker, TimeRange};

    let ticker = Ticker::new("AAPL").await?;
    let dividends = ticker.dividends(TimeRange::FiveYears).await?;
    let analytics = finance_query::DividendAnalytics::from_dividends(&dividends);

    println!("Total paid:      ${:.2}", analytics.total_paid);
    println!("Payments:        {}", analytics.payment_count);
    println!("Average payment: ${:.4}", analytics.average_payment);

    if let Some(cagr) = analytics.cagr {
        println!("CAGR:            {:.1}%", cagr * 100.0);
    }
    if let Some(last) = &analytics.last_payment {
        println!(
            "Most recent:     ${:.4} at timestamp {}",
            last.amount, last.timestamp
        );
    }
    Ok(())
}
