// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 1342
#[cfg(feature = "sentiment")]
mod soothfast_capture_body {
    #[tokio::main]
    pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
        use finance_query::Ticker;

        let ticker = Ticker::new("AAPL").await?;
        let news = ticker.news().await?;
        for article in &news {
            if let Some(s) = &article.sentiment {
                println!("{} → {} ({:+.2})", article.title, s.label.as_str(), s.score);
            }
        }

        let overall = ticker.news_sentiment().await?;
        println!(
            "Average coverage: {} ({:+.2})",
            overall.label.as_str(),
            overall.score
        );
        Ok(())
    }
}
#[cfg(feature = "sentiment")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "sentiment"))]
fn main() {}
