// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/tickers.md line 15
use finance_query::Tickers;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let tickers = Tickers::new(vec!["AAPL", "MSFT", "GOOGL"]).await?;
    Ok(())
}
