// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/dataframe.md line 179
#[cfg(feature = "dataframe")]
mod soothfast_capture_body {
    use finance_query::{Screener, finance};

    #[tokio::main]
    pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let gainers = finance::screener(Screener::DayGainers, 50).await?;

        // Convert to DataFrame
        let df = gainers.to_dataframe()?;
        println!("{}", df);
        Ok(())
    }
}
#[cfg(feature = "dataframe")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "dataframe"))]
fn main() {}
