// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/finance.md line 482
use finance_query::finance;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let semiconductors = finance::industry("semiconductors").await?;

    println!("Industry: {}", semiconductors.name);
    if let Some(overview) = &semiconductors.overview {
        println!("  Companies: {:?}", overview.companies_count);
        println!("  Market Cap: ${:?}B", overview.market_cap.map(|m| m / 1e9));
    }

    // Top companies
    for company in semiconductors.top_companies.iter().take(5) {
        println!(
            "  {} - {}",
            company.symbol,
            company.name.as_deref().unwrap_or("")
        );
    }
    Ok(())
}
