// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/tickers.md line 416
use finance_query::{Tickers, TimeRange};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Fetch capital gains for ETFs
    let etfs = Tickers::new(vec!["SPY", "VOO", "VTI"]).await?;
    let response = etfs.capital_gains(TimeRange::TwoYears).await?;

    // Process capital gains
    for (symbol, gains) in &response.capital_gains {
        if !gains.is_empty() {
            println!("{}: {} capital gains distributions", symbol, gains.len());
            for gain in gains {
                println!(
                    "  Timestamp: {}, Amount: ${:.2}",
                    gain.timestamp, gain.amount
                );
            }
        }
    }
    Ok(())
}
