// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/translation.md line 135
#[cfg(feature = "translation")]
fn main() {
    use finance_query::translation::Lang;

    let lang = Lang::parse("zh-TW").unwrap();
    assert_eq!(lang.code(), "zh-Hant"); // region implies Traditional script
    assert!(!lang.is_english());

    assert!(Lang::parse("en-US").unwrap().is_english()); // English → translation is a no-op
    assert_eq!(Lang::parse("pt_BR").unwrap().code(), "pt"); // underscores accepted

    println!(
        "zh-TW -> code={:?} is_english={}",
        lang.code(),
        lang.is_english()
    );
    println!("pt_BR -> code={:?}", Lang::parse("pt_BR").unwrap().code());
}

#[cfg(not(feature = "translation"))]
fn main() {}
