// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 1737
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::{Frequency, StatementType, Ticker};

    let ticker = Ticker::new("AAPL").await?;

    // First call -> 1 API call
    let income_annual = ticker
        .financials(StatementType::Income, Frequency::Annual)
        .await?;

    // Same parameters -> cached
    let income_annual_again = ticker
        .financials(StatementType::Income, Frequency::Annual)
        .await?;

    // Different parameters -> new API call
    let income_quarterly = ticker
        .financials(StatementType::Income, Frequency::Quarterly)
        .await?;
    let balance_annual = ticker
        .financials(StatementType::Balance, Frequency::Annual)
        .await?;

    println!("income_annual metrics: {}", income_annual.statement.len());
    println!(
        "income_annual == income_annual_again: {}",
        income_annual.statement.len() == income_annual_again.statement.len()
    );
    println!(
        "income_quarterly metrics: {}",
        income_quarterly.statement.len()
    );
    println!("balance_annual metrics: {}", balance_annual.statement.len());
    Ok(())
}
