// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 981
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::Ticker;

    let ticker = Ticker::new("AAPL").await?;

    // Get all available expiration dates and options
    let options = ticker.options(None).await?;

    // expiration_dates() and strikes() are methods
    println!("Available expiration dates:");
    for exp in options.expiration_dates() {
        println!("  {}", exp); // Unix timestamp (i64)
    }

    // calls() and puts() return a Contracts collection
    println!("\nCalls:");
    for call in &*options.calls() {
        println!(
            "  Strike ${:.2}: last=${:.2}, volume={}",
            call.strike,
            call.last_price.unwrap_or(0.0),
            call.volume.unwrap_or(0),
        );
    }

    println!("\nPuts:");
    for put in &*options.puts() {
        println!(
            "  Strike ${:.2}: last=${:.2}, IV={:.4}",
            put.strike,
            put.last_price.unwrap_or(0.0),
            put.implied_volatility.unwrap_or(0.0),
        );
    }

    // Get options for a specific expiration date
    let exp_dates = options.expiration_dates();
    if exp_dates.len() > 1 {
        let options_dated = ticker.options(Some(exp_dates[1])).await?;
        println!(
            "\nExpiration {}: {} calls, {} puts",
            exp_dates[1],
            options_dated.calls().len(),
            options_dated.puts().len()
        );
    }
    Ok(())
}
