// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/index.md line 152
fn main() {
    use finance_query::{Fetch, Provider};

    let strategy = Fetch::Sequential;
    assert_eq!(strategy, Fetch::Sequential);
    assert_ne!(Fetch::Parallel, Fetch::Sequential);

    // Yahoo is the default provider; EDGAR is likewise always compiled in.
    assert_eq!(Provider::default(), Provider::Yahoo);
    assert_eq!(Provider::Edgar.as_str(), "edgar");
    println!("default provider = {:?}", Provider::default());
    println!("Edgar.as_str()   = {:?}", Provider::Edgar.as_str());
}
