// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 15
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::Ticker;

    let _ticker = Ticker::new("AAPL").await?;
    Ok(())
}
