// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/dataframe.md line 282
#[cfg(feature = "dataframe")]
mod soothfast_capture_body {
    use finance_query::{Interval, Ticker, TimeRange};
    use polars::prelude::*;

    #[tokio::main]
    pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let ticker = Ticker::new("AAPL").await?;
        let chart = ticker.chart(Interval::OneDay, TimeRange::SixMonths).await?;
        let df = chart.to_dataframe()?;

        // Keep only high-volume days
        let high_volume = df
            .clone()
            .lazy()
            .filter(col("volume").gt(lit(50_000_000i64)))
            .collect()?;

        println!(
            "Total days: {}, high-volume days: {}",
            df.height(),
            high_volume.height()
        );
        Ok(())
    }
}
#[cfg(feature = "dataframe")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "dataframe"))]
fn main() {}
