// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/translation.md line 235
#[cfg(feature = "translation")]
mod soothfast_capture_body {
    use finance_query::translation::{self, Lang, TranslationBackend};
    use std::sync::Arc;

    struct MyBackend;

    #[async_trait::async_trait]
    impl TranslationBackend for MyBackend {
        fn id(&self) -> &'static str {
            "my-backend"
        }

        async fn translate_batch(
            &self,
            texts: &[String],
            target: &Lang,
        ) -> finance_query::Result<Vec<String>> {
            // Call your translation service; return one string per input, in order.
            let _ = target;
            Ok(texts.to_vec())
        }
    }

    #[tokio::main]
    pub async fn main() {
        translation::set_backend(Arc::new(MyBackend));

        // Not in the built-in dictionary, so this routes to the custom backend,
        // which just echoes its input back unchanged.
        let lang = Lang::parse("es").unwrap();
        let translated = translation::translate_texts(["Quantum flux capacitor"], &lang)
            .await
            .unwrap();
        println!("{:?}", translated);
    }
}
#[cfg(feature = "translation")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "translation"))]
fn main() {}
