// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/tickers.md line 835
use finance_query::format::Raw;
use finance_query::{Interval, Tickers, TimeRange};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let tickers = Tickers::new(vec!["AAPL", "MSFT"]).await?;

    // Get single quote (uses cache if available)
    let aapl = tickers.quote::<Raw>("AAPL").await?;

    // Get single chart (uses cache if available)
    let msft_chart = tickers
        .chart("MSFT", Interval::OneDay, TimeRange::OneMonth)
        .await?;

    println!("{}: price={:?}", aapl.symbol, aapl.regular_market_price);
    println!(
        "{}: candles={}",
        msft_chart.symbol,
        msft_chart.candles.len()
    );
    Ok(())
}
