// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 827
#[cfg(feature = "risk")]
mod soothfast_capture_body {
    #[tokio::main]
    pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
        use finance_query::{Interval, Ticker, TimeRange};

        let ticker = Ticker::new("AAPL").await?;

        // With S&P 500 as benchmark (enables beta calculation)
        let _risk = ticker
            .risk(Interval::OneDay, TimeRange::OneYear, Some("^GSPC"))
            .await?;

        // Without a benchmark
        let risk = ticker
            .risk(Interval::OneDay, TimeRange::OneYear, None)
            .await?;

        println!("VaR 95%:      {:.2}%", risk.var_95 * 100.0);
        println!("Max Drawdown: {:.2}%", risk.max_drawdown * 100.0);
        if let Some(sharpe) = risk.sharpe {
            println!("Sharpe:       {:.2}", sharpe);
        }
        if let Some(beta) = risk.beta {
            println!("Beta:         {:.2}", beta);
        }
        Ok(())
    }
}
#[cfg(feature = "risk")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "risk"))]
fn main() {}
