// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/futures.md line 65
#[cfg(feature = "polygon")]
fn main() {
    use finance_query::FuturesQuote;

    // `FuturesQuote` is #[non_exhaustive] outside the crate, so construct via
    // serde. With live data: `providers.futures("ES").quote().await?`.
    let quote: FuturesQuote = serde_json::from_value(serde_json::json!({
        "symbol": "ESM26",
        "name": "E-mini S&P 500 Jun 2026",
        "underlying": "S&P 500",
        "exchange": "CME",
        "expiration_date": "2026-06-19",
        "price": 5432.25,
        "change": 12.50,
        "change_percent": 0.23,
        "open_interest": 1_850_000_u64,
        "volume": 920_000_u64,
        "timestamp": 1_718_000_000_i64,
    }))
    .unwrap();

    fn verify_futures_quote_fields(q: FuturesQuote) {
        let _: String = q.symbol;
        let _: Option<String> = q.name;
        let _: Option<String> = q.underlying;
        let _: Option<String> = q.exchange;
        let _: Option<String> = q.expiration_date;
        let _: Option<f64> = q.price;
        let _: Option<f64> = q.change;
        let _: Option<f64> = q.change_percent;
        let _: Option<u64> = q.open_interest;
        let _: Option<u64> = q.volume;
        let _: Option<i64> = q.timestamp;
    }
    verify_futures_quote_fields(quote.clone());

    println!("symbol = {}", quote.symbol);
    println!("price = {:?}", quote.price);
    println!("open_interest = {:?}", quote.open_interest);
}

#[cfg(not(feature = "polygon"))]
fn main() {}
