// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 113
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::Ticker;
    use finance_query::format::Raw;

    // Enable logo fetching via builder
    let ticker = Ticker::builder("AAPL").logo().build().await?;
    let quote = ticker.quote::<Raw>().await?;

    println!("Symbol: {}", quote.symbol);
    println!("Name: {}", quote.short_name.as_deref().unwrap_or("N/A"));
    let price = quote.regular_market_price.unwrap_or(0.0);
    println!("Price: ${:.2}", price);
    let change = quote.regular_market_change.unwrap_or(0.0);
    let change_pct = quote.regular_market_change_percent.unwrap_or(0.0);
    println!("Change: {:+.2} ({:+.2}%)", change, change_pct);
    let market_cap = quote.market_cap.unwrap_or(0);
    println!("Market Cap: ${}", market_cap);
    // Logo URLs (only populated when .logo() is used on the builder)
    println!("Logo: {:?}", quote.logo_url);
    println!("Company Logo: {:?}", quote.company_logo_url);
    Ok(())
}
