// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 734
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::indicators::PatternSentiment;
    use finance_query::{Interval, Ticker, TimeRange};

    let ticker = Ticker::new("AAPL").await?;
    let chart = ticker
        .chart(Interval::OneDay, TimeRange::ThreeMonths)
        .await?;

    // Returns Vec<Option<CandlePattern>>, 1:1 aligned with chart.candles
    let signals = chart.patterns();

    // Zip patterns with candles for context
    for (candle, pattern) in chart.candles.iter().zip(signals.iter()) {
        if let Some(p) = pattern {
            println!(
                "timestamp={}: {:?} ({:?})",
                candle.timestamp,
                p,
                p.sentiment()
            );
        }
    }

    // Count bullish signals in the period
    let bullish_count = signals
        .iter()
        .filter(|s| {
            s.map(|p| p.sentiment() == PatternSentiment::Bullish)
                .unwrap_or(false)
        })
        .count();
    println!("{bullish_count} bullish patterns detected");
    Ok(())
}
