// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 1160
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::{EventKind, Ticker, TimeRange};

    let ticker = Ticker::new("AAPL").await?;
    let events = ticker.calendar(TimeRange::ThreeMonths).await?;

    for event in &events {
        let symbol = event.symbol.as_deref().unwrap_or("market");
        match &event.event {
            EventKind::Earnings {
                eps_estimate_avg, ..
            } => {
                println!(
                    "{} {} earnings, est. EPS {:?}",
                    event.date, symbol, eps_estimate_avg
                );
            }
            EventKind::ExDividend { .. } => println!("{} {} ex-dividend", event.date, symbol),
            EventKind::DividendPayment { .. } => {
                println!("{} {} dividend paid", event.date, symbol)
            }
            EventKind::OptionsExpiration { .. } => {
                println!("{} {} options expire", event.date, symbol)
            }
            _ => println!("{} {} event", event.date, symbol),
        }
    }
    Ok(())
}
