// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/finance.md line 556
use finance_query::finance;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let news = finance::news().await?;

    for article in news.iter().take(10) {
        println!("{}", article.title);
        println!("  Source: {}", article.source);
        println!("  Time: {}", article.time);
        println!("  Link: {}", article.link);
    }
    Ok(())
}
