// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/finance.md line 602
use finance_query::finance;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Get the latest transcript
    let latest = finance::earnings_transcript("AAPL", None, None).await?;
    println!("Quarter: {} {}", latest.quarter(), latest.year());
    println!(
        "Speakers: {}",
        latest.transcript_content.speaker_mapping.len()
    );

    // Get specific quarter
    let _q4_2024 = finance::earnings_transcript("AAPL", Some("Q4"), Some(2024)).await?;

    // Get all available transcripts
    let all = finance::earnings_transcripts("MSFT", None).await?;
    println!("Found {} transcripts", all.len());

    // Get only recent transcripts
    let recent = finance::earnings_transcripts("NVDA", Some(5)).await?;
    for t in &recent {
        println!(
            "{}: {} {}",
            t.title,
            t.transcript.quarter(),
            t.transcript.year()
        );
    }
    Ok(())
}
