// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/forex.md line 97
#[cfg(feature = "alphavantage")]
fn main() {
    use finance_query::ForexQuote;

    // `ForexQuote` is #[non_exhaustive] outside the crate, so construct via
    // serde. With live data: `providers.forex("EUR", "USD").quote().await?`.
    let quote: ForexQuote = serde_json::from_value(serde_json::json!({
        "symbol": "EURUSD",
        "base_currency": "EUR",
        "quote_currency": "USD",
        "bid": 1.084250,
        "ask": 1.084400,
        "price": 1.084325,
        "change": 0.001200,
        "change_percent": 0.1108,
        "timestamp": 1_718_000_000_i64,
    }))
    .unwrap();

    fn verify_forex_quote_fields(q: ForexQuote) {
        let _: String = q.symbol;
        let _: Option<String> = q.base_currency;
        let _: Option<String> = q.quote_currency;
        let _: Option<f64> = q.bid;
        let _: Option<f64> = q.ask;
        let _: Option<f64> = q.price;
        let _: Option<f64> = q.change;
        let _: Option<f64> = q.change_percent;
        let _: Option<i64> = q.timestamp;
    }
    verify_forex_quote_fields(quote.clone());

    println!("symbol = {}", quote.symbol);
    println!("bid = {:?}, ask = {:?}", quote.bid, quote.ask);
    println!("price = {:?}", quote.price);
}

#[cfg(not(feature = "alphavantage"))]
fn main() {}
