// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/dataframe.md line 350
#[cfg(feature = "dataframe")]
mod soothfast_capture_body {
    use finance_query::{Interval, Ticker, TimeRange};
    use polars::prelude::*;

    #[tokio::main]
    pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let ticker = Ticker::new("AAPL").await?;
        let chart = ticker.chart(Interval::OneDay, TimeRange::OneMonth).await?;
        let df = chart.to_dataframe()?;

        // Add daily return column
        let df = df
            .lazy()
            .with_column(
                ((col("close") - col("close").shift(lit(1))) / col("close").shift(lit(1))
                    * lit(100.0))
                .alias("daily_return_pct"),
            )
            .collect()?;

        println!("{:?}", df.column("daily_return_pct")?);
        Ok(())
    }
}
#[cfg(feature = "dataframe")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "dataframe"))]
fn main() {}
