// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/finance.md line 759
use finance_query::finance;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let exchanges = finance::exchanges().await?;

    for exchange in &exchanges {
        println!(
            "{} - {} (suffix: {})",
            exchange.country, exchange.market, exchange.suffix
        );
    }
    Ok(())
}
