// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/dataframe.md line 439
#[cfg(feature = "dataframe")]
mod soothfast_capture_body {
    use finance_query::{Screener, finance};
    use polars::prelude::*;

    #[tokio::main]
    pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
        let gainers = finance::screener(Screener::DayGainers, 100).await?;

        let mut df = gainers.to_dataframe()?;

        // Sort by market cap descending
        df = df.sort(
            ["market_cap"],
            SortMultipleOptions::default().with_order_descending(true),
        )?;

        // Get top 10
        let top_10 = df.head(Some(10));
        println!("{}", top_10);
        Ok(())
    }
}
#[cfg(feature = "dataframe")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "dataframe"))]
fn main() {}
