// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/tickers.md line 99
use finance_query::{Capability, Fetch, Provider, Providers};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let providers = Providers::builder()
        .route(Capability::QUOTE, [Provider::Yahoo])
        .fetch(Fetch::Sequential)
        .build()
        .await?;
    let tickers = providers.tickers(["AAPL", "NVDA"]).build().await?;
    let response = tickers.quotes().await?;
    println!("quotes fetched: {}", response.quotes.len());
    Ok(())
}
