// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/indices.md line 180
#[cfg(feature = "polygon")]
mod soothfast_capture_body {
    use finance_query::{Chart, IndexQuote};

    // `IndexQuote` and `Chart` are #[non_exhaustive] with no public constructor
    // outside the crate, but both derive `Deserialize` — build real instances via serde.
    pub fn main() {
        let quote: IndexQuote = serde_json::from_value(serde_json::json!({
            "symbol": "I:SPX",
            "name": "S&P 500",
            "price": 5123.45,
            "change": 12.34,
            "change_percent": 0.24,
            "timestamp": 1_700_000_000_i64
        }))
        .unwrap();

        let chart: Chart = serde_json::from_value(serde_json::json!({
            "symbol": "I:SPX",
            "meta": { "symbol": "I:SPX" },
            "candles": [
                {"timestamp": 1_700_000_000_i64, "open": 5100.0, "high": 5150.0, "low": 5080.0, "close": 5123.45, "volume": 2_400_000_000_i64}
            ]
        }))
        .unwrap();

        println!("quote: {} = {:?}", quote.symbol, quote.price);
        println!("candles: {}", chart.candles.len());
        println!("close: {:.2}", chart.candles[0].close);
    }
}
#[cfg(feature = "polygon")]
pub use soothfast_capture_body::main;

#[cfg(not(feature = "polygon"))]
fn main() {}
