// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 699
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::indicators::{rsi, sma};
    use finance_query::{Interval, Ticker, TimeRange};

    let ticker = Ticker::new("AAPL").await?;
    let chart = ticker.chart(Interval::OneDay, TimeRange::OneMonth).await?;
    let closes: Vec<f64> = chart.candles.iter().map(|c| c.close).collect();

    let sma_25 = sma(&closes, 25);
    let rsi_10 = rsi(&closes, 10)?;

    if let Some(&latest) = sma_25.last().and_then(|v| v.as_ref()) {
        println!("SMA(25): {:.2}", latest);
    }
    if let Some(&latest) = rsi_10.last().and_then(|v| v.as_ref()) {
        println!("RSI(10): {:.2}", latest);
    }
    Ok(())
}
