// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/ticker.md line 603
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    use finance_query::{Interval, Ticker, TimeRange};

    let ticker = Ticker::new("AAPL").await?;
    let indicators = ticker
        .indicators(Interval::OneDay, TimeRange::ThreeMonths)
        .await?;

    // Simple indicators (Option<f64>)
    if let Some(rsi) = indicators.rsi_14 {
        println!("RSI(14): {:.2}", rsi);
        if rsi < 30.0 {
            println!("  -> Oversold");
        } else if rsi > 70.0 {
            println!("  -> Overbought");
        }
    }

    if let Some(sma) = indicators.sma_200 {
        println!("SMA(200): {:.2}", sma);
    }

    // Compound indicators (Option<Struct>)
    if let Some(macd) = &indicators.macd
        && let (Some(line), Some(signal)) = (macd.macd, macd.signal)
    {
        println!("MACD: {:.4} | Signal: {:.4}", line, signal);
        if line > signal {
            println!("  -> Bullish");
        }
    }

    if let Some(bb) = &indicators.bollinger_bands
        && let (Some(upper), Some(lower)) = (bb.upper, bb.lower)
    {
        println!("Bollinger: Upper={:.2}, Lower={:.2}", upper, lower);
    }
    Ok(())
}
