// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/providers/index.md line 111
fn main() {
    use finance_query::Capability;

    let market_data = Capability::QUOTE | Capability::CHART;
    assert!(market_data.contains(Capability::QUOTE));
    assert!(market_data.contains(Capability::CHART));
    assert!(!market_data.contains(Capability::OPTIONS));
    assert_eq!(Capability::QUOTE.name(), "quote");
    println!("market_data = {market_data:?}");
    println!("QUOTE.name() = {:?}", Capability::QUOTE.name());
}
