// @generated by `cargo soothfast docs gen-tests`
// source: docs/library/indicators.md line 407
#[cfg(feature = "indicators")]
fn main() {
    use finance_query::indicators::{CandlePattern, PatternSentiment};

    // `signals` has the shape returned by `patterns()` / `chart.patterns()`
    let signals = [
        Some(CandlePattern::BullishEngulfing),
        None,
        Some(CandlePattern::ShootingStar),
        Some(CandlePattern::Doji),
    ];

    let bullish = signals
        .iter()
        .filter(|s| {
            s.map(|p| p.sentiment() == PatternSentiment::Bullish)
                .unwrap_or(false)
        })
        .count();

    let bearish = signals
        .iter()
        .filter(|s| {
            s.map(|p| p.sentiment() == PatternSentiment::Bearish)
                .unwrap_or(false)
        })
        .count();

    // Doji is Neutral — counted in neither bucket
    assert_eq!((bullish, bearish), (1, 1));
    println!("Bull/Bear ratio: {}/{}", bullish, bearish);
}

#[cfg(not(feature = "indicators"))]
fn main() {}
