use ratatui::style::Color;

/// Categories of available indicators
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IndicatorCategory {
    PriceAction,
    MovingAverages,
    Oscillators,
    Trend,
    Volatility,
    Volume,
    Momentum,
}

impl IndicatorCategory {
    pub fn all() -> Vec<Self> {
        vec![
            Self::PriceAction,
            Self::MovingAverages,
            Self::Oscillators,
            Self::Trend,
            Self::Volatility,
            Self::Volume,
            Self::Momentum,
        ]
    }

    pub fn name(&self) -> &'static str {
        match self {
            Self::PriceAction => "Price Action",
            Self::MovingAverages => "Moving Averages",
            Self::Oscillators => "Oscillators",
            Self::Trend => "Trend",
            Self::Volatility => "Volatility",
            Self::Volume => "Volume",
            Self::Momentum => "Momentum",
        }
    }

    pub fn color(&self) -> Color {
        match self {
            Self::PriceAction => Color::White,
            Self::MovingAverages => Color::Cyan,
            Self::Oscillators => Color::Magenta,
            Self::Trend => Color::Yellow,
            Self::Volatility => Color::Red,
            Self::Volume => Color::Green,
            Self::Momentum => Color::Blue,
        }
    }
}

/// Definition of an indicator with its parameters
#[derive(Debug, Clone)]
pub struct IndicatorDef {
    pub name: &'static str,
    pub code: &'static str,
    pub description: &'static str,
    pub category: IndicatorCategory,
    pub params: Vec<ParamDef>,
    /// Typical range for this indicator (for comparison suggestions)
    pub typical_range: Option<(f64, f64)>,
}

/// Parameter definition for an indicator
#[derive(Debug, Clone)]
pub struct ParamDef {
    pub name: &'static str,
    pub description: &'static str,
    pub default: f64,
    pub min: f64,
    pub max: f64,
    pub step: f64,
}

impl IndicatorDef {
    pub fn all() -> Vec<Self> {
        vec![
            // Price Action - derived from OHLCV data without complex calculations
            Self {
                name: "Close Price",
                code: "close",
                description: "Current closing price",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Open Price",
                code: "open",
                description: "Current opening price",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "High Price",
                code: "high",
                description: "Current high price",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Low Price",
                code: "low",
                description: "Current low price",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Volume",
                code: "volume",
                description: "Trading volume",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Price Change %",
                code: "price_change_pct",
                description: "Percentage change from previous close",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: Some((-10.0, 10.0)),
            },
            Self {
                name: "Gap %",
                code: "gap_pct",
                description: "Gap percentage (open vs previous close)",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: Some((-5.0, 5.0)),
            },
            Self {
                name: "Candle Range",
                code: "candle_range",
                description: "High minus Low (volatility proxy)",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Candle Body",
                code: "candle_body",
                description: "Absolute difference between open and close",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Is Bullish",
                code: "is_bullish",
                description: "1.0 if close > open, 0.0 otherwise",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: Some((0.0, 1.0)),
            },
            Self {
                name: "Is Bearish",
                code: "is_bearish",
                description: "1.0 if close < open, 0.0 otherwise",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: Some((0.0, 1.0)),
            },
            Self {
                name: "Relative Volume",
                code: "relative_volume",
                description: "Current volume divided by N-period average volume",
                category: IndicatorCategory::PriceAction,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Average volume lookback period",
                    default: 20.0,
                    min: 5.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((0.0, 5.0)),
            },
            Self {
                name: "Typical Price",
                code: "typical_price",
                description: "(High + Low + Close) / 3",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Median Price",
                code: "median_price",
                description: "(High + Low) / 2",
                category: IndicatorCategory::PriceAction,
                params: vec![],
                typical_range: None,
            },
            // Moving Averages
            Self {
                name: "Simple Moving Average",
                code: "sma",
                description: "Average of closing prices over N periods",
                category: IndicatorCategory::MovingAverages,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 20.0,
                    min: 2.0,
                    max: 500.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Exponential Moving Average",
                code: "ema",
                description: "Weighted average giving more weight to recent prices",
                category: IndicatorCategory::MovingAverages,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 12.0,
                    min: 2.0,
                    max: 500.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Weighted Moving Average",
                code: "wma",
                description: "Linearly weighted moving average",
                category: IndicatorCategory::MovingAverages,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 20.0,
                    min: 2.0,
                    max: 500.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Double EMA",
                code: "dema",
                description: "Double exponential moving average - reduces lag",
                category: IndicatorCategory::MovingAverages,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 20.0,
                    min: 2.0,
                    max: 500.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Triple EMA",
                code: "tema",
                description: "Triple exponential moving average - even less lag",
                category: IndicatorCategory::MovingAverages,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 20.0,
                    min: 2.0,
                    max: 500.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Hull Moving Average",
                code: "hma",
                description: "Fast and smooth moving average",
                category: IndicatorCategory::MovingAverages,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 20.0,
                    min: 2.0,
                    max: 500.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Volume Weighted MA",
                code: "vwma",
                description: "Moving average weighted by volume",
                category: IndicatorCategory::MovingAverages,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 20.0,
                    min: 2.0,
                    max: 500.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "McGinley Dynamic",
                code: "mcginley",
                description: "Self-adjusting moving average",
                category: IndicatorCategory::MovingAverages,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 14.0,
                    min: 2.0,
                    max: 500.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            // Oscillators
            Self {
                name: "Relative Strength Index",
                code: "rsi",
                description: "Momentum oscillator measuring speed of price changes",
                category: IndicatorCategory::Oscillators,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 14.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((0.0, 100.0)),
            },
            Self {
                name: "Stochastic %K",
                code: "stochastic",
                description: "Compares closing price to price range",
                category: IndicatorCategory::Oscillators,
                params: vec![
                    ParamDef {
                        name: "K Period",
                        description: "%K period",
                        default: 14.0,
                        min: 1.0,
                        max: 100.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "K Slow",
                        description: "%K smoothing",
                        default: 3.0,
                        min: 1.0,
                        max: 20.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "D Period",
                        description: "%D period",
                        default: 3.0,
                        min: 1.0,
                        max: 20.0,
                        step: 1.0,
                    },
                ],
                typical_range: Some((0.0, 100.0)),
            },
            Self {
                name: "Commodity Channel Index",
                code: "cci",
                description: "Measures deviation from statistical mean",
                category: IndicatorCategory::Oscillators,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 20.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((-200.0, 200.0)),
            },
            Self {
                name: "Williams %R",
                code: "williams_r",
                description: "Momentum indicator similar to Stochastic",
                category: IndicatorCategory::Oscillators,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 14.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((-100.0, 0.0)),
            },
            Self {
                name: "Chande Momentum",
                code: "cmo",
                description: "Momentum oscillator measuring trend strength",
                category: IndicatorCategory::Oscillators,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 14.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((-100.0, 100.0)),
            },
            Self {
                name: "Awesome Oscillator",
                code: "awesome_oscillator",
                description: "Difference between 5 and 34 period SMAs of median price",
                category: IndicatorCategory::Oscillators,
                params: vec![
                    ParamDef {
                        name: "Fast",
                        description: "Fast period",
                        default: 5.0,
                        min: 2.0,
                        max: 50.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Slow",
                        description: "Slow period",
                        default: 34.0,
                        min: 5.0,
                        max: 100.0,
                        step: 1.0,
                    },
                ],
                typical_range: None,
            },
            Self {
                name: "Stochastic RSI",
                code: "stochastic_rsi",
                description: "Stochastic applied to RSI values",
                category: IndicatorCategory::Oscillators,
                params: vec![
                    ParamDef {
                        name: "RSI Period",
                        description: "RSI calculation period",
                        default: 14.0,
                        min: 2.0,
                        max: 50.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Stoch Period",
                        description: "Stochastic period",
                        default: 14.0,
                        min: 2.0,
                        max: 50.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "K Smooth",
                        description: "%K smoothing",
                        default: 3.0,
                        min: 1.0,
                        max: 10.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "D Smooth",
                        description: "%D smoothing",
                        default: 3.0,
                        min: 1.0,
                        max: 10.0,
                        step: 1.0,
                    },
                ],
                typical_range: Some((0.0, 100.0)),
            },
            // Trend Indicators
            Self {
                name: "MACD",
                code: "macd",
                description: "Moving Average Convergence Divergence",
                category: IndicatorCategory::Trend,
                params: vec![
                    ParamDef {
                        name: "Fast",
                        description: "Fast EMA period",
                        default: 12.0,
                        min: 2.0,
                        max: 50.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Slow",
                        description: "Slow EMA period",
                        default: 26.0,
                        min: 5.0,
                        max: 100.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Signal",
                        description: "Signal line period",
                        default: 9.0,
                        min: 2.0,
                        max: 50.0,
                        step: 1.0,
                    },
                ],
                typical_range: None,
            },
            Self {
                name: "Average Directional Index",
                code: "adx",
                description: "Measures trend strength (not direction)",
                category: IndicatorCategory::Trend,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 14.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((0.0, 100.0)),
            },
            Self {
                name: "Aroon",
                code: "aroon",
                description: "Identifies trend changes and strength",
                category: IndicatorCategory::Trend,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 25.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((0.0, 100.0)),
            },
            Self {
                name: "SuperTrend",
                code: "supertrend",
                description: "Trend-following indicator using ATR",
                category: IndicatorCategory::Trend,
                params: vec![
                    ParamDef {
                        name: "Period",
                        description: "ATR period",
                        default: 10.0,
                        min: 1.0,
                        max: 50.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Multiplier",
                        description: "ATR multiplier",
                        default: 3.0,
                        min: 0.5,
                        max: 10.0,
                        step: 0.1,
                    },
                ],
                typical_range: None,
            },
            Self {
                name: "Parabolic SAR",
                code: "parabolic_sar",
                description: "Stop and reverse indicator for trend following",
                category: IndicatorCategory::Trend,
                params: vec![
                    ParamDef {
                        name: "Step",
                        description: "Acceleration factor",
                        default: 0.02,
                        min: 0.01,
                        max: 0.2,
                        step: 0.01,
                    },
                    ParamDef {
                        name: "Max",
                        description: "Maximum acceleration",
                        default: 0.2,
                        min: 0.1,
                        max: 0.5,
                        step: 0.01,
                    },
                ],
                typical_range: None,
            },
            Self {
                name: "Ichimoku Cloud",
                code: "ichimoku",
                description: "Comprehensive trend and support/resistance indicator",
                category: IndicatorCategory::Trend,
                params: vec![
                    ParamDef {
                        name: "Tenkan",
                        description: "Conversion line period",
                        default: 9.0,
                        min: 2.0,
                        max: 50.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Kijun",
                        description: "Base line period",
                        default: 26.0,
                        min: 5.0,
                        max: 100.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Senkou",
                        description: "Leading span B period",
                        default: 52.0,
                        min: 10.0,
                        max: 200.0,
                        step: 1.0,
                    },
                ],
                typical_range: None,
            },
            // Volatility
            Self {
                name: "Bollinger Bands",
                code: "bollinger",
                description: "Volatility bands around moving average",
                category: IndicatorCategory::Volatility,
                params: vec![
                    ParamDef {
                        name: "Period",
                        description: "MA period",
                        default: 20.0,
                        min: 2.0,
                        max: 100.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Std Dev",
                        description: "Standard deviations",
                        default: 2.0,
                        min: 0.5,
                        max: 4.0,
                        step: 0.1,
                    },
                ],
                typical_range: None,
            },
            Self {
                name: "Average True Range",
                code: "atr",
                description: "Measures market volatility",
                category: IndicatorCategory::Volatility,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 14.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Donchian Channels",
                code: "donchian",
                description: "Highest high and lowest low over N periods",
                category: IndicatorCategory::Volatility,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 20.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Keltner Channels",
                code: "keltner",
                description: "Volatility channels using ATR",
                category: IndicatorCategory::Volatility,
                params: vec![
                    ParamDef {
                        name: "Period",
                        description: "EMA period",
                        default: 20.0,
                        min: 2.0,
                        max: 100.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Multiplier",
                        description: "ATR multiplier",
                        default: 2.0,
                        min: 0.5,
                        max: 5.0,
                        step: 0.1,
                    },
                    ParamDef {
                        name: "ATR Period",
                        description: "ATR calculation period",
                        default: 10.0,
                        min: 2.0,
                        max: 50.0,
                        step: 1.0,
                    },
                ],
                typical_range: None,
            },
            Self {
                name: "Choppiness Index",
                code: "choppiness_index",
                description: "Determines if market is trending or ranging",
                category: IndicatorCategory::Volatility,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 14.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((0.0, 100.0)),
            },
            // Volume
            Self {
                name: "On-Balance Volume",
                code: "obv",
                description: "Cumulative volume based on price direction",
                category: IndicatorCategory::Volume,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Volume Weighted Avg Price",
                code: "vwap",
                description: "Average price weighted by volume",
                category: IndicatorCategory::Volume,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Money Flow Index",
                code: "mfi",
                description: "Volume-weighted RSI",
                category: IndicatorCategory::Volume,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 14.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((0.0, 100.0)),
            },
            Self {
                name: "Chaikin Money Flow",
                code: "cmf",
                description: "Measures buying/selling pressure",
                category: IndicatorCategory::Volume,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 20.0,
                    min: 2.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: Some((-1.0, 1.0)),
            },
            Self {
                name: "Accumulation/Distribution",
                code: "accumulation_distribution",
                description: "Cumulative money flow indicator",
                category: IndicatorCategory::Volume,
                params: vec![],
                typical_range: None,
            },
            Self {
                name: "Balance of Power",
                code: "balance_of_power",
                description: "Measures buying vs selling pressure",
                category: IndicatorCategory::Volume,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Smoothing period (0 for raw)",
                    default: 14.0,
                    min: 0.0,
                    max: 50.0,
                    step: 1.0,
                }],
                typical_range: Some((-1.0, 1.0)),
            },
            // Momentum
            Self {
                name: "Momentum",
                code: "momentum",
                description: "Rate of price change",
                category: IndicatorCategory::Momentum,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 10.0,
                    min: 1.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Rate of Change",
                code: "roc",
                description: "Percentage change in price",
                category: IndicatorCategory::Momentum,
                params: vec![ParamDef {
                    name: "Period",
                    description: "Number of periods",
                    default: 12.0,
                    min: 1.0,
                    max: 100.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Coppock Curve",
                code: "coppock_curve",
                description: "Long-term momentum indicator",
                category: IndicatorCategory::Momentum,
                params: vec![
                    ParamDef {
                        name: "WMA Period",
                        description: "WMA period",
                        default: 10.0,
                        min: 2.0,
                        max: 50.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Long ROC",
                        description: "Long ROC period",
                        default: 14.0,
                        min: 5.0,
                        max: 50.0,
                        step: 1.0,
                    },
                    ParamDef {
                        name: "Short ROC",
                        description: "Short ROC period",
                        default: 11.0,
                        min: 2.0,
                        max: 30.0,
                        step: 1.0,
                    },
                ],
                typical_range: None,
            },
            Self {
                name: "Bull Power",
                code: "bull_power",
                description: "Elder Bull Power (high - EMA)",
                category: IndicatorCategory::Momentum,
                params: vec![ParamDef {
                    name: "Period",
                    description: "EMA period",
                    default: 13.0,
                    min: 2.0,
                    max: 50.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
            Self {
                name: "Bear Power",
                code: "bear_power",
                description: "Elder Bear Power (low - EMA)",
                category: IndicatorCategory::Momentum,
                params: vec![ParamDef {
                    name: "Period",
                    description: "EMA period",
                    default: 13.0,
                    min: 2.0,
                    max: 50.0,
                    step: 1.0,
                }],
                typical_range: None,
            },
        ]
    }

    /// Get all indicators in a specific category
    pub fn by_category(category: IndicatorCategory) -> Vec<Self> {
        Self::all()
            .into_iter()
            .filter(|i| i.category == category)
            .collect()
    }
}
