name: AWS Deploy

on:
  push:
    branches: [ "master" ]
    # Also trigger on workflow_dispatch for manual deployments
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: finance
  FUNCTION_NAME: FinanceQuery

jobs:

  aws-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container using the specified Dockerfile and
          # push it to ECR so that it can be deployed to ECS.
          docker build -f Dockerfile.aws -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --image-uri ${{ env.image }} --region ${{ env.AWS_REGION }} > /dev/null
